const Parts_List = require("../models/partList");

const part_list = {
  addNewPart: (req, res) => {
    //   const arr = [
    //       { name: 'A/C Accumulator'},
    //  { name: 'A/C Accumulator with Hose Assembly'},
    //  { name: 'A/C Block Off Kit'},
    //  { name: 'A/C Blower Control Unit'},
    //  { name: 'A/C Clutch'},
    //  { name: 'A/C Compressor'},
    //  { name: 'A/C Compressor Clutch Kit'},
    //  { name: 'A/C Compressor Control Valve'},
    //  { name: 'A/C Compressor Kit'},
    //  { name: 'A/C Condenser'},
    //  { name: 'A/C Condenser and Receiver Drier Assembly'},
    //  { name: 'A/C Condenser Fan Assembly'},
    //  { name: 'A/C Condenser Fan Motor'},
    //  { name: 'A/C Condenser Fan Shroud'},
    //  { name: 'A/C Control Panel'},
    //  { name: 'A/C Control Switch'},
    //  { name: 'A/C Evaporator'},
    //  { name: 'A/C Evaporator Core Repair Kit'},
    //  { name: 'A/C Evaporator Temperature Sensor'},
    //  { name: 'A/C Heater Control'},
    //  { name: 'A/C Hose'},
    //  { name: 'A/C Liquid Line Assembly'},
    //  { name: 'A/C Liquid Line with Orifice Tube'},
    //  { name: 'A/C Manifold Hose Assembly'},
    //  { name: 'A/C Pipe'},
    //  { name: 'A/C Pressure Switch'},
    //  { name: 'A/C Receiver Drier'},
    //  { name: 'A/C Refrigerant Discharge / Suction Hose Assembly'},
    //  { name: 'A/C Refrigerant Discharge Hose'},
    //  { name: 'A/C Refrigerant Liquid Hose'},
    //  { name: 'A/C Refrigerant Suction Hose'},
    //  { name: 'A/C Refrigerant Temperature Sensor'},
    //  { name: 'A/C Selector Switch'},
    //  { name: 'A/C Servo'},
    //  { name: 'A/C Suction and Liquid Line Hose Assembly'},
    //  { name: 'A/C Suction Line Hose Assembly'},
    //  { name: 'A/C Wiring Harness'},
    //  { name: 'ABS Accumulator'},
    //  { name: 'ABS Control Unit'},
    //  { name: 'ABS Hydraulic Unit'},
    //  { name: 'ABS Modulator Valve'},
    //  { name: 'ABS Pressure Monitor Switch'},
    //  { name: 'ABS Pump'},
    //  { name: 'ABS Repair Kit'},
    //  { name: 'ABS Ring'},
    //  { name: 'ABS Speed Sensor'},
    //  { name: 'ABS Speed Sensor Kit'},
    //  { name: 'ABS Wheel Speed Sensor Set'},
    //  { name: 'ABS Wheel Speed Sensor Wire Harness'},
    //  { name: 'Accelerator Pedal'},
    //  { name: 'Accelerator Pedal Assembly'},
    //  { name: 'Accelerator Pedal Sensor'},
    //  { name: 'Accessory Belt Idler Assembly'},
    //  { name: 'Accessory Belt Idler Pulley'},
    //  { name: 'Accessory Belt Tension Adjuster'},
    //  { name: 'Accessory Belt Tension Pulley'},
    //  { name: 'Accessory Belt Tensioner'},
    //  { name: 'Accessory Belt Tensioner Assembly'},
    //  { name: 'Accessory Belt Tensioner Bracket'},
    //  { name: 'Accessory Drive Belt Kit'},
    //  { name: 'Accessory Power Outlet (110 Volt)'},
    //  { name: 'Accessory Shaft Coupling Kit'},
    //  { name: 'Accumulator'},
    //  { name: 'Actuator (4WD)'},
    //  { name: 'Actuator Valve (4WD)'},
    //  { name: 'Air Bag Clockspring'},
    //  { name: 'Air Bag Sensor Connector'},
    //  { name: 'Air Compressor'},
    //  { name: 'Air Distribution Duct Clip'},
    //  { name: 'Air Duct Housing'},
    //  { name: 'Air Filter'},
    //  { name: 'Air Filter Housing'},
    //  { name: 'Air Filter Housing Clamp'},
    //  { name: 'Air Filter Set'},
    //  { name: 'Air Flap Actuator'},
    //  { name: 'Air Fuel Ratio Sensor'},
    //  { name: 'Air Inject Check Valve'},
    //  { name: 'Air Intake Heater Relay'},
    //  { name: 'Air Intake Hose'},
    //  { name: 'Air Intake Hose Set'},
    //  { name: 'Air Intake Kit'},
    //  { name: 'Air Intake Resonator'},
    //  { name: 'Air Lift Leveling Kit'},
    //  { name: 'Air Mass Meter'},
    //  { name: 'Air Mass Meter Boot'},
    //  { name: 'Air Mass Meter Hose'},
    //  { name: 'Air Mass Sensor'},
    //  { name: 'Air Mass Sensor Clip'},
    //  { name: 'Air Pump'},
    //  { name: 'Air Pump Check Valve'},
    //  { name: 'Air Pump Control Valve'},
    //  { name: 'Air Pump Hose'},
    //  { name: 'Air Pump Rubber Mount'},
    //  { name: 'Air Spring'},
    //  { name: 'Air Spring Conversion Kit'},
    //  { name: 'Air Spring to Coil Spring Conversion Kit'},
    //  { name: 'Air Strut and Shock Kit'},
    //  { name: 'Air Suspension Compressor and Strut Kit'},
    //  { name: 'Air Suspension Compressor Kit'},
    //  { name: 'Air Suspension Compressor Strut Spring Kit'},
    //  { name: 'Air Suspension Shock'},
    //  { name: 'Air Suspension Solenoid Valve Unit'},
    //  { name: 'Air Suspension Spring Set'},
    //  { name: 'Air Suspension Strut Set'},
    //  { name: 'Air Temperature Sensor'},
    //  { name: 'Alarm Siren'},
    //  { name: 'Alignment Cam Bolt'},
    //  { name: 'Alignment Camber Lateral Link'},
    //  { name: 'Alignment Caster Camber Kit'},
    //  { name: 'Alternator'},
    //  { name: 'Alternator Cable'},
    //  { name: 'Alternator Mount Bracket'},
    //  { name: 'Alternator Pulley'},
    //  { name: 'Altitude Sensor'},
    //  { name: 'Ambient Temp Sensor'},
    //  { name: 'Antenna'},
    //  { name: 'Antenna - Power'},
    //  { name: 'Antenna Base'},
    //  { name: 'Antenna Bracket'},
    //  { name: 'Antenna Cover'},
    //  { name: 'Antenna Mast'},
    //  { name: 'Antenna Seal'},
    //  { name: 'Audio Amplifier'},
    //  { name: 'Auto Dual Clutch Actuator'},
    //  { name: 'Auto Trans Filler Tube'},
    //  { name: 'Auto Trans Master Repair Kit'},
    //  { name: 'Auto Trans Oil Cooler Hose Assembly'},
    //  { name: 'Auto Trans Oil Cooler Tube'},
    //  { name: 'Auto Trans Oil Pan and Filter Kit'},
    //  { name: 'Auto Trans Oil Pressure Switch'},
    //  { name: 'Auto Trans Shift Cable Bushing'},
    //  { name: 'Auto Trans Shift Cover Plate'},
    //  { name: 'Auto Trans Shift Lever Assembly'},
    //  { name: 'Auto Trans Shift Lever Button'},
    //  { name: 'Auto Trans Shift Lever Kit'},
    //  { name: 'Auto Trans Shift Lever Knob'},
    //  { name: 'Auto Trans Shift Lever Solenoid'},
    //  { name: 'Auto Trans Shift Tube'},
    //  { name: 'Auto Trans Shifter Cable Kit'},
    //  { name: 'Auto Trans Shifter Repair Kit'},
    //  { name: 'Auto Trans Solenoid Gasket'},
    //  { name: 'Auto Trans Solenoid Kit'},
    //  { name: 'Auto Trans Throttle Valve Cable'},
    //  { name: 'Auto Trans Torque Converter'},
    //  { name: 'Auto Transmission Shift Cable'},
    //  { name: 'Automatic Transmission Cooling Hose'},
    //  { name: 'Automatic Transmission Dipstick'},
    //  { name: 'Automatic Transmission Filter'},
    //  { name: 'Automatic Transmission Filter Kit'},
    //  { name: 'Automatic Transmission Front Pump'},
    //  { name: 'Automatic Transmission Input Shaft Speed Sensor'},
    //  { name: 'Automatic Transmission Oil Cooler'},
    //  { name: 'Automatic Transmission Output Shaft Speed Sensor'},
    //  { name: 'Automatic Transmission Pan'},
    //  { name: 'Automatic Transmission Pan Gasket'},
    //  { name: 'Automatic Transmission Selector Cable'},
    //  { name: 'Automatic Transmission Selector Handle'},
    //  { name: 'Automatic Transmission Shift Linkage Bushing'},
    //  { name: 'Automatic Transmission Solenoid'},
    //  { name: 'Automatic Transmission Speed Sensor'},
    //  { name: 'Automatic Transmission Wire Harness'},
    //  { name: 'Auxiliary Air Valve'},
    //  { name: 'Auxiliary Engine Cooling Fan Assembly'},
    //  { name: 'Auxiliary Fan Assembly'},
    //  { name: 'Auxiliary Fan Control Unit'},
    //  { name: 'Auxiliary Fan Motor'},
    //  { name: 'Auxiliary Fan Relay'},
    //  { name: 'Auxiliary Fan Resistor'},
    //  { name: 'Auxiliary Fan Switch'},
    //  { name: 'Auxiliary Water Pump'},
    //  { name: 'AWD Coupling Oil Pump'},
    //  { name: 'Axle Actuator Housing (4WD)'},
    //  { name: 'Axle and Wheel Bearing Kit'},
    //  { name: 'Axle and Wheel Hub Assembly Kit'},
    //  { name: 'Axle Assembly'},
    //  { name: 'Axle Ball Joint Tie Rod End Kit'},
    //  { name: 'Axle Bearing and Hub Assembly Repair Kit'},
    //  { name: 'Axle Bearing Carrier'},
    //  { name: 'Axle Differential Bearing and Seal Kit'},
    //  { name: 'Axle Flip Kit'},
    //  { name: 'Axle Nut'},
    //  { name: 'Axle Seal'},
    //  { name: 'Axle Shaft'},
    //  { name: 'Axle Shaft Bearing'},
    //  { name: 'Axle Shaft Bearing Kit'},
    //  { name: 'Axle Shaft Kit'},
    //  { name: 'Axle Shaft Seal'},
    //  { name: 'Axle Shaft Set'},
    //  { name: 'Axle Shaft Universal Joint'},
    //  { name: 'Axle Spindle'},
    //  { name: 'Axle Wheel Hub Ball Joint Tie Rod Kit'},
    //  { name: 'Axle Wheel Hub Tie Rod End Kit'},
    //  { name: 'Back Glass Lift Support Kit'},
    //  { name: 'Back Up Lamp Assembly'},
    //  { name: 'Back Up Lamp Connector'},
    //  { name: 'Back Up Lamp Socket'},
    //  { name: 'Back Up Light'},
    //  { name: 'Back Up Light Lens'},
    //  { name: 'Back Up Light Switch'},
    //  { name: 'Balance Shaft'},
    //  { name: 'Balance Shaft Kit'},
    //  { name: 'Ball Joint'},
    //  { name: 'Ball Joint and Tie Rod End Kit'},
    //  { name: 'Ball Joint and Tie Rod Kit'},
    //  { name: 'Ball Joint Kit'},
    //  { name: 'Ball Joint Set'},
    //  { name: 'Ball Joint Shim'},
    //  { name: 'Ball Joint Sway Bar Link Tie Rod End Kit'},
    //  { name: 'Ball Joint Tie Rod and Center Link Kit'},
    //  { name: 'Ball Joint Tie Rod End Center Link Kit'},
    //  { name: 'Ball Joint Tie Rod End Drag Link Kit'},
    //  { name: 'Ball Joint Tie Rod End Idler Arm Kit'},
    //  { name: 'Ball Joint Tie Rod Pitman Idler Arm Kit'},
    //  { name: 'Ball Joints Tie Rods Idler and Pitman Arm Kit'},
    //  { name: 'Ball Joints Tie Rods Sway Bar Link Idler and Center Link Kit'},
    //  { name: 'Ball Joints Tie Rods Sway Bar Link Kit'},
    //  { name: 'Ball Joints Tie Rods Sway Bar Links Idler and Pitman Arm Kit'},
    //  { name: 'Ball Joints Tie Rods Sway Bar Links Idler Arm Kit'},
    //  { name: 'Battery'},
    //  { name: 'Battery Cable'},
    //  { name: 'Battery Cable End'},
    //  { name: 'Battery Cable Harness'},
    //  { name: 'Battery Cable Positive'},
    //  { name: 'Battery Cover'},
    //  { name: 'Battery Current Sensor'},
    //  { name: 'Battery Current Sensor Connector'},
    //  { name: 'Battery Power Distribution Box'},
    //  { name: 'Battery Terminal'},
    //  { name: 'Battery Tray'},
    //  { name: 'Bed Liner'},
    //  { name: 'Bed Mat'},
    //  { name: 'Bed Rack'},
    //  { name: 'Bed Rail to Rail Tool Box'},
    //  { name: 'Bed Side Rail Protector'},
    //  { name: 'Belt Tensioner Kit'},
    //  { name: 'Blind Spot Detection System Warning Sensor'},
    //  { name: 'Blower Control Switch'},
    //  { name: 'Blower Motor'},
    //  { name: 'Blower Motor Regulator'},
    //  { name: 'Blower Motor Resistor'},
    //  { name: 'Blower Motor Switch'},
    //  { name: 'Blower Motor Wiring Harness'},
    //  { name: 'Body A-Pillar Trim Panel'},
    //  { name: 'Body Harness Connector'},
    //  { name: 'Body Lift Kit'},
    //  { name: 'Body Lowering Kit'},
    //  { name: 'Body Moulding Kit'},
    //  { name: 'Body Mount'},
    //  { name: 'Body Mount Set'},
    //  { name: 'Body Seal Kit'},
    //  { name: 'Boost Pressure Sensor'},
    //  { name: 'Boost Pressure Valve'},
    //  { name: 'Booster Vacuum Hose'},
    //  { name: 'Booster Vacuum Switch'},
    //  { name: 'Brake / Tail / Turn Signal Light Connector'},
    //  { name: 'Brake Adjuster'},
    //  { name: 'Brake and Clutch Pedal Assembly'},
    //  { name: 'Brake Backing Plate'},
    //  { name: 'Brake Booster'},
    //  { name: 'Brake Booster Line'},
    //  { name: 'Brake Booster Vacuum Hose'},
    //  { name: 'Brake Booster Vacuum Pump'},
    //  { name: 'Brake Caliper'},
    //  { name: 'Brake Caliper Bolt'},
    //  { name: 'Brake Caliper Carrier'},
    //  { name: 'Brake Caliper Set'},
    //  { name: 'Brake Drum'},
    //  { name: 'Brake Drum and Brake Shoe Kit'},
    //  { name: 'Brake Drum Set'},
    //  { name: 'Brake Drum Shoe and Wheel Cylinder Kit'},
    //  { name: 'Brake Dust Shield'},
    //  { name: 'Brake Dust Shield Set'},
    //  { name: 'Brake Hose'},
    //  { name: 'Brake Hydraulic Hose Kit'},
    //  { name: 'Brake Hydraulic Line Kit'},
    //  { name: 'Brake Light'},
    //  { name: 'Brake Line'},
    //  { name: 'Brake Master Cylinder'},
    //  { name: 'Brake Pad and Rotor and Wheel Hub Kit'},
    //  { name: 'Brake Pad and Rotor Kit'},
    //  { name: 'Brake Pad Rotor Shoe Drum Kit'},
    //  { name: 'Brake Pad Sensor'},
    //  { name: 'Brake Pad Sensor Kit'},
    //  { name: 'Brake Pad Set'},
    //  { name: 'Brake Pedal Pad'},
    //  { name: 'Brake Pedal Position Sensor'},
    //  { name: 'Brake Pressure Switch Connector'},
    //  { name: 'Brake Proportioning Valve'},
    //  { name: 'Brake Reservoir'},
    //  { name: 'Brake Reservoir Cap'},
    //  { name: 'Brake Rotor'},
    //  { name: 'Brake Rotor and Hub Assembly'},
    //  { name: 'Brake Rotor Set'},
    //  { name: 'Brake Rotor Set Screw'},
    //  { name: 'Brake Shoe Set'},
    //  { name: 'Brake Vacuum Hose'},
    //  { name: 'Breather Hose'},
    //  { name: 'Bug Shield'},
    //  { name: 'Bulb'},
    //  { name: 'Bulb - Headlight'},
    //  { name: 'Bulb Socket'},
    //  { name: 'Bumper'},
    //  { name: 'Bumper Absorber'},
    //  { name: 'Bumper Air Deflector'},
    //  { name: 'Bumper Bracket'},
    //  { name: 'Bumper Cover'},
    //  { name: 'Bumper Cover Bracket'},
    //  { name: 'Bumper Cover Grille'},
    //  { name: 'Bumper Cover Grille Molding'},
    //  { name: 'Bumper Cover Molding'},
    //  { name: 'Bumper Cover Reflector'},
    //  { name: 'Bumper Cover Reinforcement'},
    //  { name: 'Bumper Cover Retainer'},
    //  { name: 'Bumper Cover Shield'},
    //  { name: 'Bumper Cover Stiffener'},
    //  { name: 'Bumper Cover Support'},
    //  { name: 'Bumper Cover Trim Panel'},
    //  { name: 'Bumper Deflector'},
    //  { name: 'Bumper End'},
    //  { name: 'Bumper End Cap'},
    //  { name: 'Bumper Face Bar'},
    //  { name: 'Bumper Filler'},
    //  { name: 'Bumper Grille'},
    //  { name: 'Bumper Grille Insert'},
    //  { name: 'Bumper Grille Molding'},
    //  { name: 'Bumper Guard'},
    //  { name: 'Bumper Guard Set'},
    //  { name: 'Bumper Impact Bar Brace'},
    //  { name: 'Bumper Impact Strip'},
    //  { name: 'Bumper Insert'},
    //  { name: 'Bumper Molding'},
    //  { name: 'Bumper Moulding'},
    //  { name: 'Bumper Moulding Insert'},
    //  { name: 'Bumper Mounting Kit'},
    //  { name: 'Bumper Protection Pad'},
    //  { name: 'Bumper Reflector'},
    //  { name: 'Bumper Reinforcement'},
    //  { name: 'Bumper Splash Shield'},
    //  { name: 'Bumper Spoiler'},
    //  { name: 'Bumper Trim'},
    //  { name: 'Bumper Valance'},
    //  { name: 'Bypass Hose'},
    //  { name: 'Cab Corner'},
    //  { name: 'Cab Corner and Rocker Panel Kit'},
    //  { name: 'Cab Corner Set'},
    //  { name: 'Cab Protector and Headache Rack'},
    //  { name: 'Cabin Air Filter'},
    //  { name: 'Cabin Air Filter Cover'},
    //  { name: 'Cabin Air Filter Retrofit Kit'},
    //  { name: 'Cabin Air Filter Set'},
    //  { name: 'Caliper Piston'},
    //  { name: 'Cam Follower'},
    //  { name: 'Cam Plug'},
    //  { name: 'Camshaft'},
    //  { name: 'Camshaft Adjuster Magnet'},
    //  { name: 'Camshaft Bearing Set'},
    //  { name: 'Camshaft Gear'},
    //  { name: 'Camshaft Kit'},
    //  { name: 'Camshaft Lock Tool'},
    //  { name: 'Camshaft Position Sensor'},
    //  { name: 'Camshaft Position Sensor Set'},
    //  { name: 'Camshaft Seal'},
    //  { name: 'Camshaft Solenoid Adjuster'},
    //  { name: 'Camshaft Synchronizer'},
    //  { name: 'Cap Emblem'},
    //  { name: 'Car Cover'},
    //  { name: 'Carbon Canister'},
    //  { name: 'Carburetor'},
    //  { name: 'Carburetor Kit'},
    //  { name: 'Carburetor Repair Kit'},
    //  { name: 'Cargo Liner'},
    //  { name: 'Catalytic Converter'},
    //  { name: 'Catalytic Converter and Pipe Assembly'},
    //  { name: 'Catalytic Converter Gasket'},
    //  { name: 'CD ROM Repair Manual'},
    //  { name: 'Center Cap'},
    //  { name: 'Center Console'},
    //  { name: 'Center Console Base'},
    //  { name: 'Center Console Latch'},
    //  { name: 'Central Lock Switch'},
    //  { name: 'Chain Tensioner Update Kit'},
    //  { name: 'Circuit Opening Relay'},
    //  { name: 'Climate Control Button Set'},
    //  { name: 'Climate Control Module'},
    //  { name: 'Climate Control Push Button Set'},
    //  { name: 'Clutch Cable'},
    //  { name: 'Clutch Disc'},
    //  { name: 'Clutch Flywheel Conversion Kit'},
    //  { name: 'Clutch Hose'},
    //  { name: 'Clutch Hydraulic Line'},
    //  { name: 'Clutch Installation Tool'},
    //  { name: 'Clutch Kit'},
    //  { name: 'Clutch Lever'},
    //  { name: 'Clutch Master Cylinder'},
    //  { name: 'Clutch Master Cylinder and Line Assembly'},
    //  { name: 'Clutch Master/Slave Assembly'},
    //  { name: 'Clutch Pedal'},
    //  { name: 'Clutch Pedal Ignition Lock Switch'},
    //  { name: 'Clutch Pedal Pad'},
    //  { name: 'Clutch Pedal Stop Pad'},
    //  { name: 'Clutch Release Arm'},
    //  { name: 'Clutch Slave Cylinder'},
    //  { name: 'Clutch Starter Safety Switch'},
    //  { name: 'Clutch Switch'},
    //  { name: 'Coil Spring'},
    //  { name: 'Coil Spring Bracket'},
    //  { name: 'Coil Spring Insulator'},
    //  { name: 'Coil Spring Lowering Kit / Shock Absorber Kit'},
    //  { name: 'Coil Spring Seat Repair Kit'},
    //  { name: 'Coil Spring Set'},
    //  { name: 'Cold Air Intake'},
    //  { name: 'Cold Air Intake Tube'},
    //  { name: 'Cold Start Valve'},
    //  { name: 'Combination Switch'},
    //  { name: 'Combination Valve'},
    //  { name: 'Combustion Detection Module'},
    //  { name: 'Computer Chip Programmer'},
    //  { name: 'Computer Control Relay'},
    //  { name: 'Console Lid'},
    //  { name: 'Control Arm'},
    //  { name: 'Control Arm and Ball Joint Assembly'},
    //  { name: 'Control Arm and Ball Joint Assembly Set'},
    //  { name: 'Control Arm and Ball Joint Kit'},
    //  { name: 'Control Arm and Sway Bar Link Kit'},
    //  { name: 'Control Arm and Tie Rod End Kit'},
    //  { name: 'Control Arm Ball Bushing'},
    //  { name: 'Control Arm Ball Joint Sway Bar Link Kit'},
    //  { name: 'Control Arm Ball Joint Tie Rod and Sway Bar Link Kit'},
    //  { name: 'Control Arm Ball Joint Tie Rod End Kit'},
    //  { name: 'Control Arm Ball Joint Tie Rod Kit'},
    //  { name: 'Control Arm Bushing'},
    //  { name: 'Control Arm Bushing Kit'},
    //  { name: 'Control Arm Kit'},
    //  { name: 'Control Arm Kit with Ball Joints and Tie Rods'},
    //  { name: 'Control Arm Kit with Tie Rods Ball Joints and Sway Bar Links'},
    //  { name: 'Control Arm Link'},
    //  { name: 'Control Arm Repair Kit'},
    //  { name: 'Control Arm Set'},
    //  { name: 'Control Arm Shaft Kit'},
    //  { name: 'Control Arm Stop'},
    //  { name: 'Control Arm Strut'},
    //  { name: 'Control Arm Support Bracket Kit'},
    //  { name: 'Control Arm Sway Bar Link Ball Joint Kit'},
    //  { name: 'Control Arm Sway Bar Link Tie Rod Kit'},
    //  { name: 'Control Arm Tie Rod and Center Link Kit'},
    //  { name: 'Control Arm Tie Rod Pitman Idler Arm Kit'},
    //  { name: 'Control Arm Wheel Hub Ball Joint Kit'},
    //  { name: 'Control Arm Wheel Hub Tie Rod End Kit'},
    //  { name: 'Converter Heat Shield'},
    //  { name: 'Convertible Top Cover Hinge'},
    //  { name: 'Convertible Top Cover Shock'},
    //  { name: 'Convertible Top Cylinder'},
    //  { name: 'Convertible Top Frame Guide Bracket'},
    //  { name: 'Convertible Top Hinge'},
    //  { name: 'Convertible Top Hydraulic Cylinder'},
    //  { name: 'Convertible Top Hydraulic Hose'},
    //  { name: 'Convertible Top Hydraulic Pump'},
    //  { name: 'Convertible Top Hydraulic Pump Fluid'},
    //  { name: 'Convertible Top Lock Assembly'},
    //  { name: 'Convertible Top Locking Handle'},
    //  { name: 'Convertible Top Motor'},
    //  { name: 'Convertible Top Push Rod'},
    //  { name: 'Convertible Top Relay'},
    //  { name: 'Convertible Top Repair Kit'},
    //  { name: 'Convertible Top Strut'},
    //  { name: 'Convertible Top Sunroof Mechanism Set'},
    //  { name: 'Convertible Top Switch'},
    //  { name: 'Convertible Top Transmission Gear'},
    //  { name: 'Coolant Antifreeze'},
    //  { name: 'Coolant Heat Storage Tank Pump'},
    //  { name: 'Coolant Hose Flange'},
    //  { name: 'Coolant Level Sensor'},
    //  { name: 'Coolant Outlet Flange'},
    //  { name: 'Coolant Outlet Housing'},
    //  { name: 'Coolant Pipe'},
    //  { name: 'Coolant Pipe Kit'},
    //  { name: 'Coolant Recovery Tank Mounting Plate'},
    //  { name: 'Coolant Thermostat Housing Bolt'},
    //  { name: 'Coolant Thermostat Kit'},
    //  { name: 'Coolant Water Outlet Housing Kit'},
    //  { name: 'Cooling Fan Hub'},
    //  { name: 'Cooling Hose'},
    //  { name: 'Cooling Hose Connector'},
    //  { name: 'Cooling Hose Flange'},
    //  { name: 'Cornering Light'},
    //  { name: 'Cornering Light Assembly'},
    //  { name: 'Cornering Light Bulb'},
    //  { name: 'Cowl Cover'},
    //  { name: 'Cowl Grille Panel'},
    //  { name: 'Cowl Grille Screen'},
    //  { name: 'Cowl Hood Panel'},
    //  { name: 'Cowl Panel'},
    //  { name: 'Cowl Seal'},
    //  { name: 'Crank Position Sensor'},
    //  { name: 'Crankcase Breather Element'},
    //  { name: 'Crankcase Breather Hose'},
    //  { name: 'Crankcase Breather Hose Kit'},
    //  { name: 'Crankcase Vent Valve'},
    //  { name: 'Crankcase Vent Valve and Breather Hose Kit'},
    //  { name: 'Crankshaft Gear'},
    //  { name: 'Crankshaft Pulley'},
    //  { name: 'Crankshaft Pulley Bolt'},
    //  { name: 'Crankshaft Seal'},
    //  { name: 'Crankshaft Woodruff Key'},
    //  { name: 'Crossover Pipe'},
    //  { name: 'Cruise Control Distance Sensor'},
    //  { name: 'Cruise Control Switch'},
    //  { name: 'Cruise Control Transducer'},
    //  { name: 'Cruise Cut Out Switch'},
    //  { name: 'Cup Holder'},
    //  { name: 'CV Axle Assembly'},
    //  { name: 'CV Axle Support Bearing Bracket'},
    //  { name: 'CV Boot'},
    //  { name: 'CV Boot Kit'},
    //  { name: 'CV Intermediate Shaft'},
    //  { name: 'CV Joint'},
    //  { name: 'CV Joint Kit'},
    //  { name: 'Cylinder Head'},
    //  { name: 'Cylinder Head Gasket Set'},
    //  { name: 'Cylinder Head Temperature Sensor'},
    //  { name: 'Dash Board Air Vent'},
    //  { name: 'Dash Board Cover'},
    //  { name: 'Dash Cover'},
    //  { name: 'Dash Panel'},
    //  { name: 'Dash Panel Patch'},
    //  { name: 'Daytime Running Lamp Socket'},
    //  { name: 'Daytime Running Light'},
    //  { name: 'Deck Lid'},
    //  { name: 'Deck Lid Finish Panel'},
    //  { name: 'Diesel Emissions Fluid Heater'},
    //  { name: 'Diesel Emissions Fluid Injection Nozzle'},
    //  { name: 'Diesel Emissions Fluid Pump'},
    //  { name: 'Diesel Exhaust Fluid (DEF) Injector'},
    //  { name: 'Diesel Fuel Injection Prechamber'},
    //  { name: 'Diesel Fuel Injector Line'},
    //  { name: 'Diesel Fuel Injector Pump'},
    //  { name: 'Diesel Fuel Injector Pump Pressure Relief Valve'},
    //  { name: 'Diesel Fuel Thermostat'},
    //  { name: 'Diesel Glow Plug Wiring Harness'},
    //  { name: 'Diesel Injection Control Pressure Sensor'},
    //  { name: 'Diesel Injector'},
    //  { name: 'Diesel Injector Driver Module'},
    //  { name: 'Diesel Injector Hose'},
    //  { name: 'Diesel Injector Nozzle'},
    //  { name: 'Diesel Particulate Filter'},
    //  { name: 'Diesel Particulate Sensor'},
    //  { name: 'Diesel Vacuum Pump'},
    //  { name: 'Differential Bearing Kit'},
    //  { name: 'Differential Carrier Bushing'},
    //  { name: 'Differential Cover'},
    //  { name: 'Differential Dynamic Dampener'},
    //  { name: 'Differential Lock Actuator'},
    //  { name: 'Differential Mount'},
    //  { name: 'Differential Mount Bushing'},
    //  { name: 'Differential Ring and Pinion'},
    //  { name: 'Differential Shift Actuator'},
    //  { name: 'Direct Ignition Coil'},
    //  { name: 'Direct Ignition Coil Boot'},
    //  { name: 'Direct Ignition Coil Kit'},
    //  { name: 'Direct Injection High Pressure Fuel Pump'},
    //  { name: 'Disc Brake Hub'},
    //  { name: 'Disc Brake Kit'},
    //  { name: 'Disc Brake Upgrade Kit'},
    //  { name: 'Disconnect (4WD)'},
    //  { name: 'Distributor Cap'},
    //  { name: 'Distributor Cap and Rotor Kit'},
    //  { name: 'Distributor Cap Gasket'},
    //  { name: 'Distributor Cap Rotor Spark Plugs and Wires Kit'},
    //  { name: 'Distributor Rotor'},
    //  { name: 'Distributor Seal'},
    //  { name: 'Dome Light Clip'},
    //  { name: 'Door'},
    //  { name: 'Door Ajar Switch Connector'},
    //  { name: 'Door Applique'},
    //  { name: 'Door Arm Rest'},
    //  { name: 'Door Belt Molding'},
    //  { name: 'Door Check'},
    //  { name: 'Door Contact Switch'},
    //  { name: 'Door Glass Attaching Clips'},
    //  { name: 'Door Glass Trim'},
    //  { name: 'Door Handle'},
    //  { name: 'Door Handle Clip'},
    //  { name: 'Door Handle Set'},
    //  { name: 'Door Harness Connector'},
    //  { name: 'Door Hinge'},
    //  { name: 'Door Hinge Pin & Bushing Kit'},
    //  { name: 'Door Hinge Repair Kit'},
    //  { name: 'Door Hinge Set'},
    //  { name: 'Door Interior Panel'},
    //  { name: 'Door Interior Trim Panel'},
    //  { name: 'Door Latch Assembly'},
    //  { name: 'Door Latch Assembly Set'},
    //  { name: 'Door Latch Cable'},
    //  { name: 'Door Latch Cable Repair Kit'},
    //  { name: 'Door Latch Release'},
    //  { name: 'Door Lock'},
    //  { name: 'Door Lock Actuator'},
    //  { name: 'Door Lock Actuator Motor'},
    //  { name: 'Door Lock Actuator Motor Set'},
    //  { name: 'Door Lock and Window Switch'},
    //  { name: 'Door Lock Assembly'},
    //  { name: 'Door Lock Kit'},
    //  { name: 'Door Lock Rod Grommet'},
    //  { name: 'Door Lock Set with Keys'},
    //  { name: 'Door Lock Striker'},
    //  { name: 'Door Mirror Cover'},
    //  { name: 'Door Mirror Drive Motor'},
    //  { name: 'Door Mirror Glass'},
    //  { name: 'Door Mirror Mount Cover'},
    //  { name: 'Door Mirror Set'},
    //  { name: 'Door Mirror Turn Signal Light'},
    //  { name: 'Door Mirror Turn Signal Light Set'},
    //  { name: 'Door Molding'},
    //  { name: 'Door Molding Set'},
    //  { name: 'Door Open Warning Switch'},
    //  { name: 'Door Panel Insert'},
    //  { name: 'Door Panel Install Kit'},
    //  { name: 'Door Remote Mirror Switch'},
    //  { name: 'Door Seal'},
    //  { name: 'Door Seal Kit'},
    //  { name: 'Door Seal Set'},
    //  { name: 'Door Shell'},
    //  { name: 'Door Sill Panel Clip'},
    //  { name: 'Door Skin'},
    //  { name: 'Door Window Belt Weatherstrip'},
    //  { name: 'Door Window Belt Weatherstrip Kit'},
    //  { name: 'Door Window Belt Weatherstrip Set'},
    //  { name: 'Door Window Switch Bezel'},
    //  { name: 'Door Wiring Harness'},
    //  { name: 'Drag Link'},
    //  { name: 'Drip Rail Molding'},
    //  { name: 'Drive Axle Assembly'},
    //  { name: 'Drive Belt Idler Assembly'},
    //  { name: 'Drive Belt Tensioner Pulley'},
    //  { name: 'Drive Belt Tensioner Tool'},
    //  { name: 'Drive Motor Battery Fan Assyembly'},
    //  { name: 'Drive Shaft Center Support Bearing'},
    //  { name: 'Drive Shaft Coupler'},
    //  { name: 'Drive Shaft CV Joint'},
    //  { name: 'Drive Shaft Flex Joint'},
    //  { name: 'Drive Shaft Flex Joint Kit'},
    //  { name: 'Drive Shaft Repair Kit'},
    //  { name: 'Driveshaft'},
    //  { name: 'Driveshaft CV Joint'},
    //  { name: 'Driveshaft CV Joint Kit'},
    //  { name: 'Driveshaft Support'},
    //  { name: 'Driveshaft Support Bearing'},
    //  { name: 'Drum Brake Hardware Kit'},
    //  { name: 'Drum Brake Shoe Kit'},
    //  { name: 'Dual Clutch Flywheel'},
    //  { name: 'Eccentric Shaft Sensor'},
    //  { name: 'ECU Relay'},
    //  { name: 'EGR Cooler'},
    //  { name: 'EGR Cooler Bypass Valve'},
    //  { name: 'EGR Cooler Hose'},
    //  { name: 'EGR Line'},
    //  { name: 'EGR Pressure Feedback Sensor'},
    //  { name: 'EGR Tube'},
    //  { name: 'EGR Vacuum Solenoid'},
    //  { name: 'EGR Valve'},
    //  { name: 'EGR Valve Control Switch'},
    //  { name: 'EHA Valve'},
    //  { name: 'Electric Change Over Valve'},
    //  { name: 'Electric Fuel Pump'},
    //  { name: 'Electronic Control Unit'},
    //  { name: 'Electronic Throttle Body Actuator Connector'},
    //  { name: 'Emblem'},
    //  { name: 'Emblem Set'},
    //  { name: 'Engine Camshaft'},
    //  { name: 'Engine Connecting Rod'},
    //  { name: 'Engine Control Module'},
    //  { name: 'Engine Coolant Air Bleed Pipe'},
    //  { name: 'Engine Coolant Bypass Valve'},
    //  { name: 'Engine Coolant Filler Neck'},
    //  { name: 'Engine Coolant Outlet Flange'},
    //  { name: 'Engine Coolant Overflow Tank Kit'},
    //  { name: 'Engine Coolant Thermostat Housing Assembly'},
    //  { name: 'Engine Cooling Fan'},
    //  { name: 'Engine Cooling Fan Module'},
    //  { name: 'Engine Cooling Fan Motor Connector'},
    //  { name: 'Engine Cooling Fan Pulley Bracket'},
    //  { name: 'Engine Cover'},
    //  { name: 'Engine Cradle'},
    //  { name: 'Engine Crankcase Breather Element'},
    //  { name: 'Engine Cylinder Deactivation Solenoid'},
    //  { name: 'Engine Cylinder Head Gasket Kit'},
    //  { name: 'Engine Gasket Set'},
    //  { name: 'Engine Harmonic Balancer'},
    //  { name: 'Engine Intake Manifold Installation Kit'},
    //  { name: 'Engine Mount'},
    //  { name: 'Engine Mount and Transmission Mount Kit'},
    //  { name: 'Engine Mount Bracket'},
    //  { name: 'Engine Mount Bushing'},
    //  { name: 'Engine Mount Kit'},
    //  { name: 'Engine Mount Set'},
    //  { name: 'Engine Mount Stop'},
    //  { name: 'Engine Multiple Displacement System Solenoid'},
    //  { name: 'Engine Oil Cooler and EGR Cooler Kit'},
    //  { name: 'Engine Oil Cooler Kit'},
    //  { name: 'Engine Oil Pressure Sensor'},
    //  { name: 'Engine Shock Mount'},
    //  { name: 'Engine Shock Mount Kit'},
    //  { name: 'Engine Splash Shield'},
    //  { name: 'Engine Splash Shield Hardware'},
    //  { name: 'Engine Temperature Sensor'},
    //  { name: 'Engine Timing Damper Kit'},
    //  { name: 'Engine Torque Rod'},
    //  { name: 'Engine Torque Rod Mount'},
    //  { name: 'Engine Torque Strut Bushing'},
    //  { name: 'Engine Valve Cover Set'},
    //  { name: 'Engine Variable Timing Sprocket'},
    //  { name: 'Engine Variable Valve Lift Eccentric Shaft Actuator'},
    //  { name: 'Engine Variable Valve Timing Sprocket'},
    //  { name: 'Engine Variable Valve Timing Sprocket Set'},
    //  { name: 'Engine Water Pump Kit'},
    //  { name: 'Engine Wiring Harness'},
    //  { name: 'Evaporative Emissions System Lines'},
    //  { name: 'Exhaust Bolt'},
    //  { name: 'Exhaust Clamp'},
    //  { name: 'Exhaust Flex Connector'},
    //  { name: 'Exhaust Gasket'},
    //  { name: 'Exhaust Hanger'},
    //  { name: 'Exhaust Header Kit'},
    //  { name: 'Exhaust Header Pipe'},
    //  { name: 'Exhaust Manifold'},
    //  { name: 'Exhaust Manifold Gasket'},
    //  { name: 'Exhaust Manifold Gasket Set'},
    //  { name: 'Exhaust Manifold Hardware Kit'},
    //  { name: 'Exhaust Manifold Kit'},
    //  { name: 'Exhaust Manifold Set'},
    //  { name: 'Exhaust Manifold with Integrated Catalytic Converter'},
    //  { name: 'Exhaust Mounting Kit'},
    //  { name: 'Exhaust Pipe'},
    //  { name: 'Exhaust Pipe Spout'},
    //  { name: 'Exhaust Pipe to Manifold Gasket'},
    //  { name: 'Exhaust Resonator'},
    //  { name: 'Exhaust Resonator and Pipe Assembly'},
    //  { name: 'Exhaust Spring'},
    //  { name: 'Exhaust System'},
    //  { name: 'Exhaust Tail Pipe Tip'},
    //  { name: 'Exhaust Temperature Sensor'},
    //  { name: 'Exhaust Valve'},
    //  { name: 'Exhaust Y Pipe'},
    //  { name: 'Expansion Tank'},
    //  { name: 'Expansion Tank Cap'},
    //  { name: 'Expansion Tank Hose'},
    //  { name: 'Exterior Door Handle Set'},
    //  { name: 'Exterior Molding Clip'},
    //  { name: 'Fabric Door Skins'},
    //  { name: 'Fader Control Switch'},
    //  { name: 'Fan Blade'},
    //  { name: 'Fan Clutch'},
    //  { name: 'Fan Clutch Bearing'},
    //  { name: 'Fan Clutch Bearing Bracket'},
    //  { name: 'Fan Clutch Blade'},
    //  { name: 'Fan Clutch Pulley Assembly'},
    //  { name: 'Fan Shroud'},
    //  { name: 'Fast Idle Valve Solenoid'},
    //  { name: 'Fender'},
    //  { name: 'Fender Brace'},
    //  { name: 'Fender Extension'},
    //  { name: 'Fender Flare'},
    //  { name: 'Fender Flare Set'},
    //  { name: 'Fender Flares'},
    //  { name: 'Fender Insert'},
    //  { name: 'Fender Liner'},
    //  { name: 'Fender Liner Retainer'},
    //  { name: 'Fender Liner Rivet'},
    //  { name: 'Fender Molding Retainer'},
    //  { name: 'Fifth Wheel Trailer Hitch Rail Kit'},
    //  { name: 'Firewall'},
    //  { name: 'Firewall Plate'},
    //  { name: 'Flex Fuel Sensor'},
    //  { name: 'Flex Plate'},
    //  { name: 'Floor Brace'},
    //  { name: 'Floor Hump'},
    //  { name: 'Floor Mat Set'},
    //  { name: 'Floor Shift Assembly'},
    //  { name: 'Flywheel'},
    //  { name: 'Flywheel Conversion'},
    //  { name: 'Fog Hole Cover'},
    //  { name: 'Fog Light'},
    //  { name: 'Fog Light and Bezel Kit'},
    //  { name: 'Fog Light Bezel'},
    //  { name: 'Fog Light Bracket'},
    //  { name: 'Fog Light Bulb'},
    //  { name: 'Fog Light Connector'},
    //  { name: 'Fog Light Cover'},
    //  { name: 'Fog Light Cover Set'},
    //  { name: 'Fog Light Grille'},
    //  { name: 'Fog Light Hole Insert'},
    //  { name: 'Fog Light Housing Trim'},
    //  { name: 'Fog Light Kit'},
    //  { name: 'Fog Light Lens'},
    //  { name: 'Fog Light Set'},
    //  { name: 'Fog Light Switch'},
    //  { name: 'Fog Light Trim'},
    //  { name: 'Frame Rail'},
    //  { name: 'Frame Rail Repair Kit'},
    //  { name: 'Frame Repair Kit'},
    //  { name: 'Front Body Panel'},
    //  { name: 'Fuel / Emission Vacuum Switch'},
    //  { name: 'Fuel Accumulator'},
    //  { name: 'Fuel Cooler'},
    //  { name: 'Fuel Distributor'},
    //  { name: 'Fuel Door'},
    //  { name: 'Fuel Door Cover'},
    //  { name: 'Fuel Door Hinge'},
    //  { name: 'Fuel Door Spring'},
    //  { name: 'Fuel Feed and Return Hose'},
    //  { name: 'Fuel Filler Door'},
    //  { name: 'Fuel Filler Door Kit'},
    //  { name: 'Fuel Filler Door Lock Actuator'},
    //  { name: 'Fuel Filler Neck'},
    //  { name: 'Fuel Filler Neck Grommet'},
    //  { name: 'Fuel Filler Neck Seal'},
    //  { name: 'Fuel Filter'},
    //  { name: 'Fuel Filter Cap'},
    //  { name: 'Fuel Filter Housing'},
    //  { name: 'Fuel Filter Kit'},
    //  { name: 'Fuel Injection Electro Hydraulic Actuator Valve'},
    //  { name: 'Fuel Injection Fuel Rail'},
    //  { name: 'Fuel Injection Fuel Rail Pressure Sensor'},
    //  { name: 'Fuel Injection Main Relay'},
    //  { name: 'Fuel Injection Pump'},
    //  { name: 'Fuel Injection Relay'},
    //  { name: 'Fuel Injection Thermostat'},
    //  { name: 'Fuel Injector'},
    //  { name: 'Fuel Injector Control Module'},
    //  { name: 'Fuel Injector Kit'},
    //  { name: 'Fuel Injector Puller'},
    //  { name: 'Fuel Injector Rail'},
    //  { name: 'Fuel Injector Seal Kit'},
    //  { name: 'Fuel Injector Set'},
    //  { name: 'Fuel Level Control Unit'},
    //  { name: 'Fuel Level Sending Unit'},
    //  { name: 'Fuel Level Sensor'},
    //  { name: 'Fuel Line'},
    //  { name: 'Fuel Line Set'},
    //  { name: 'Fuel Management Wiring Harness'},
    //  { name: 'Fuel Pressure Damper'},
    //  { name: 'Fuel Pressure Regulator'},
    //  { name: 'Fuel Pressure Regulator Service Kit'},
    //  { name: 'Fuel Pressure Sensor'},
    //  { name: 'Fuel Pump'},
    //  { name: 'Fuel Pump / Sending Unit Connector'},
    //  { name: 'Fuel Pump and Sender Assembly'},
    //  { name: 'Fuel Pump and Strainer Set'},
    //  { name: 'Fuel Pump Assembly'},
    //  { name: 'Fuel Pump Control Module'},
    //  { name: 'Fuel Pump Driver Module'},
    //  { name: 'Fuel Pump Flange'},
    //  { name: 'Fuel Pump Hanger'},
    //  { name: 'Fuel Pump Hanger and Gaskets'},
    //  { name: 'Fuel Pump Hanger Assembly'},
    //  { name: 'Fuel Pump Lock Ring'},
    //  { name: 'Fuel Pump Mount'},
    //  { name: 'Fuel Pump Mounting Bracket'},
    //  { name: 'Fuel Pump Relay'},
    //  { name: 'Fuel Pump Reservoir'},
    //  { name: 'Fuel Pump Tank Seal'},
    //  { name: 'Fuel Screen'},
    //  { name: 'Fuel Sender-Filter Assembly'},
    //  { name: 'Fuel Separator'},
    //  { name: 'Fuel Shut-Off Solenoid'},
    //  { name: 'Fuel Supply Hose'},
    //  { name: 'Fuel Tank'},
    //  { name: 'Fuel Tank and Pump Assembly'},
    //  { name: 'Fuel Tank Bracket'},
    //  { name: 'Fuel Tank Cap'},
    //  { name: 'Fuel Tank Crossmember'},
    //  { name: 'Fuel Tank Door Cable'},
    //  { name: 'Fuel Tank Door Latch'},
    //  { name: 'Fuel Tank Kit'},
    //  { name: 'Fuel Tank Pressure Sensor'},
    //  { name: 'Fuel Tank Roll Over Valve'},
    //  { name: 'Fuel Tank Selector Valve'},
    //  { name: 'Fuel Tank Sender Assembly'},
    //  { name: 'Fuel Tank Sending Unit and Fuel Filter Assembly'},
    //  { name: 'Fuel Tank Skid Plate'},
    //  { name: 'Fuel Tank Strap'},
    //  { name: 'Fuel Tank Vent Hose'},
    //  { name: 'Fuel Tank Vent Valve'},
    //  { name: 'Fuel Transfer Pump'},
    //  { name: 'Fuse'},
    //  { name: 'Fuse Block'},
    //  { name: 'Fuse Box'},
    //  { name: 'Fuse Holder'},
    //  { name: 'Fuse Kit'},
    //  { name: 'Fusebox'},
    //  { name: 'Fusible Link'},
    //  { name: 'Gear Selector Lever'},
    //  { name: 'Generator'},
    //  { name: 'Glove Box'},
    //  { name: 'Glove Box Door'},
    //  { name: 'Glove Box Latch'},
    //  { name: 'Glow Plug'},
    //  { name: 'Glow Plug and Connector Kit'},
    //  { name: 'Glow Plug Control Module'},
    //  { name: 'Glow Plug Kit'},
    //  { name: 'Glow Plug Relay'},
    //  { name: 'Gooseneck Trailer Hitch Kit'},
    //  { name: 'Grab Handle'},
    //  { name: 'Grille'},
    //  { name: 'Grille and Headlight Bezel Kit'},
    //  { name: 'Grille and Headlight Kit'},
    //  { name: 'Grille Assembly'},
    //  { name: 'Grille Billet Type'},
    //  { name: 'Grille Bracket'},
    //  { name: 'Grille Cover'},
    //  { name: 'Grille Emblem'},
    //  { name: 'Grille Guard'},
    //  { name: 'Grille Headlight Parking Light Kit'},
    //  { name: 'Grille Insert'},
    //  { name: 'Grille Molding'},
    //  { name: 'Grille Molding Kit'},
    //  { name: 'Grille Moulding'},
    //  { name: 'Grille Mounting Panel'},
    //  { name: 'Grille Retainer'},
    //  { name: 'Grille Shell'},
    //  { name: 'Grille Support'},
    //  { name: 'Groan Stopper Bolt Cover'},
    //  { name: 'Guide Rod'},
    //  { name: 'Guide Rod Mount'},
    //  { name: 'Guide Rod Mount Kit'},
    //  { name: 'Hatch Handle'},
    //  { name: 'Hatch Lock Solenoid'},
    //  { name: 'Hatch Seal'},
    //  { name: 'Hatch Strut'},
    //  { name: 'Hazard Flasher Switch'},
    //  { name: 'Hazard Warning and Turn Signal Flasher'},
    //  { name: 'Hazard Warning Flasher'},
    //  { name: 'Head Bolt'},
    //  { name: 'Head Bolt Set'},
    //  { name: 'Head Gasket'},
    //  { name: 'Head Gasket Set'},
    //  { name: 'Head Gasket Set With Head Bolts'},
    //  { name: 'Head Gasket Set With Head Bolts and Valves'},
    //  { name: 'Header Panel'},
    //  { name: 'Header Pipe'},
    //  { name: 'Headlamp Socket'},
    //  { name: 'Headlight Adjuster Kit'},
    //  { name: 'Headlight and Fog Light Kit'},
    //  { name: 'Headlight and Side Marker Kit'},
    //  { name: 'Headlight and Tail Light Kit'},
    //  { name: 'Headlight Assembly'},
    //  { name: 'Headlight Assembly and Bezel Set'},
    //  { name: 'Headlight Assembly and Parking Light Kit'},
    //  { name: 'Headlight Assembly Set'},
    //  { name: 'Headlight Ballast'},
    //  { name: 'Headlight Bezel'},
    //  { name: 'Headlight Bracket'},
    //  { name: 'Headlight Bucket'},
    //  { name: 'Headlight Bucket Kit'},
    //  { name: 'Headlight Bulb'},
    //  { name: 'Headlight Bulb Retainer'},
    //  { name: 'Headlight Bulb Socket'},
    //  { name: 'Headlight Carrier'},
    //  { name: 'Headlight Connector'},
    //  { name: 'Headlight Cornering Parking Light Kit'},
    //  { name: 'Headlight Dimmer Switch'},
    //  { name: 'Headlight Dimmer Switch Connector'},
    //  { name: 'Headlight Door'},
    //  { name: 'Headlight Door Bezel'},
    //  { name: 'Headlight Fog Light Cornering Light Kit'},
    //  { name: 'Headlight Fog Light Parking Light Kit'},
    //  { name: 'Headlight Frame'},
    //  { name: 'Headlight Halo Ring Bulb'},
    //  { name: 'Headlight High / Low Beam Lamp Connector'},
    //  { name: 'Headlight Igniter'},
    //  { name: 'Headlight Lens'},
    //  { name: 'Headlight Lens Housing'},
    //  { name: 'Headlight Level Sensor'},
    //  { name: 'Headlight Motor'},
    //  { name: 'Headlight Motor Gear'},
    //  { name: 'Headlight Motor Kit'},
    //  { name: 'Headlight Mount Panel'},
    //  { name: 'Headlight Mounting Panel'},
    //  { name: 'Headlight Parking Light Side Marker Kit'},
    //  { name: 'Headlight Retainer'},
    //  { name: 'Headlight Retaining Ring'},
    //  { name: 'Headlight Rim'},
    //  { name: 'Headlight Sealed Beam'},
    //  { name: 'Headlight Set'},
    //  { name: 'Headlight Switch'},
    //  { name: 'Headlight Switch Connector'},
    //  { name: 'Headlight Switch Knob'},
    //  { name: 'Headlight Tail Light Parking Light Kit'},
    //  { name: 'Headlight Trim Ring'},
    //  { name: 'Headlight Washer Nozzle'},
    //  { name: 'Headlight Wiper Blade Set'},
    //  { name: 'Headlight Wiring Harness'},
    //  { name: 'Heated Seat Module Connector'},
    //  { name: 'Heater Control Knob'},
    //  { name: 'Heater Control Panel'},
    //  { name: 'Heater Coolant Heater Control'},
    //  { name: 'Heater Core'},
    //  { name: 'Heater Core O-Ring'},
    //  { name: 'Heater Core Tube'},
    //  { name: 'Heater Hose'},
    //  { name: 'Heater Hose Connector'},
    //  { name: 'Heater Hose Set'},
    //  { name: 'Heater Knob'},
    //  { name: 'Heater Valve'},
    //  { name: 'High Pressure Injection Oil Pump'},
    //  { name: 'Hood'},
    //  { name: 'Hood Ajar Indicator Switch Connector'},
    //  { name: 'Hood and Trunk Release Switch Assembly'},
    //  { name: 'Hood Hinge'},
    //  { name: 'Hood Insulation Pad'},
    //  { name: 'Hood Latch'},
    //  { name: 'Hood Latch Striker'},
    //  { name: 'Hood Latch Support'},
    //  { name: 'Hood Lift Support Kit'},
    //  { name: 'Hood Lock'},
    //  { name: 'Hood Lock Assembly'},
    //  { name: 'Hood Molding'},
    //  { name: 'Hood Moulding'},
    //  { name: 'Hood Pad'},
    //  { name: 'Hood Pin'},
    //  { name: 'Hood Release Cable'},
    //  { name: 'Hood Release Handle'},
    //  { name: 'Hood Release Strap'},
    //  { name: 'Hood Rod Clip'},
    //  { name: 'Hood Rod Grommet'},
    //  { name: 'Hood Safety Catch'},
    //  { name: 'Hood Scoop'},
    //  { name: 'Hood Scoop Insert'},
    //  { name: 'Hood Seal'},
    //  { name: 'Hood Spring'},
    //  { name: 'Hood Stop'},
    //  { name: 'Hood Stop Buffer'},
    //  { name: 'Hood Strut'},
    //  { name: 'Hood Strut Set'},
    //  { name: 'Horizontal Fuel Conditioning Module'},
    //  { name: 'Horn'},
    //  { name: 'Horn Contact'},
    //  { name: 'Hub Cap'},
    //  { name: 'Hub Cap Kit'},
    //  { name: 'Hub Locking Actuator Set (4WD)'},
    //  { name: 'Hub Locking Solenoid (4WD)'},
    //  { name: 'Human Machine Interface Module'},
    //  { name: 'Humidity Sensor'},
    //  { name: 'HVAC Air Inlet Door Actuator'},
    //  { name: 'HVAC Auxiliary Fan Control Module'},
    //  { name: 'HVAC Blend Door Repair Kit'},
    //  { name: 'HVAC Blower Control Switch Connector'},
    //  { name: 'HVAC Blower Fan Switch'},
    //  { name: 'HVAC Blower Motor and Wheel'},
    //  { name: 'HVAC Blower Motor Connector'},
    //  { name: 'HVAC Blower Motor Control Module'},
    //  { name: 'HVAC Blower Motor Kit'},
    //  { name: 'HVAC Blower Motor Regulator'},
    //  { name: 'HVAC Blower Motor Resistor Connector'},
    //  { name: 'HVAC Blower Motor Resistor Harness'},
    //  { name: 'HVAC Blower Motor Resistor Kit'},
    //  { name: 'HVAC Control Module'},
    //  { name: 'HVAC Control Panel'},
    //  { name: 'HVAC Control Select Switch Connector'},
    //  { name: 'HVAC Heater Blend Door'},
    //  { name: 'HVAC Heater Hose Outlet Tube'},
    //  { name: 'HVAC Heater Pipe'},
    //  { name: 'HVAC Heater Pipe Set'},
    //  { name: 'HVAC Mode Control Knob Set'},
    //  { name: 'HVAC Panel Mode Door Actuator'},
    //  { name: 'HVAC Recirculation Door Actuator'},
    //  { name: 'HVAC Servo'},
    //  { name: 'HVAC Temperature Control Panel'},
    //  { name: 'HVAC Temperature Valve'},
    //  { name: 'Hybrid Battery Pack'},
    //  { name: 'Hydraulic System Fluid'},
    //  { name: 'Hydrocarbon Injector Driver Module'},
    //  { name: 'Idle Air Control Valve'},
    //  { name: 'Idle Air Control Valve Connector'},
    //  { name: 'Idle Control Unit'},
    //  { name: 'Idle Control Valve'},
    //  { name: 'Idle Speed Control Motor'},
    //  { name: 'Idle Valve Gasket'},
    //  { name: 'Idler Arm'},
    //  { name: 'Idler Arm and Bracket Kit'},
    //  { name: 'Idler Arm and Pitman Arm Kit'},
    //  { name: 'Igniter'},
    //  { name: 'Ignition Coil'},
    //  { name: 'Ignition Coil and Connector Kit'},
    //  { name: 'Ignition Coil and Spark Plug Kit'},
    //  { name: 'Ignition Coil Connector Kit'},
    //  { name: 'Ignition Coil Connector Repair Kit'},
    //  { name: 'Ignition Coil Kit'},
    //  { name: 'Ignition Coil Set'},
    //  { name: 'Ignition Coil Set with Spark Plugs'},
    //  { name: 'Ignition Control Unit'},
    //  { name: 'Ignition Distributor'},
    //  { name: 'Ignition Immobilizer'},
    //  { name: 'Ignition Knock (Detonation) Sensor'},
    //  { name: 'Ignition Knock (Detonation) Sensor Kit'},
    //  { name: 'Ignition Lock and Cylinder Switch'},
    //  { name: 'Ignition Lock Assembly'},
    //  { name: 'Ignition Lock Cylinder'},
    //  { name: 'Ignition Lock Cylinder Repair Kit'},
    //  { name: 'Ignition Lock Housing'},
    //  { name: 'Ignition Relay'},
    //  { name: 'Ignition Switch'},
    //  { name: 'Ignition Switch Actuator Pin'},
    //  { name: 'Ignition Switch Connector'},
    //  { name: 'Ignition Tune-Up Kit'},
    //  { name: 'Ignition Wire Boot Set'},
    //  { name: 'Impact Sensor'},
    //  { name: 'Impulse Sender'},
    //  { name: 'Injection Pump'},
    //  { name: 'Injection Pump Seal Kit'},
    //  { name: 'Inner Fender'},
    //  { name: 'Inner Fender Well'},
    //  { name: 'Input Shaft Bearing'},
    //  { name: 'Inside Door Handle'},
    //  { name: 'Instrument Cluster Bezel'},
    //  { name: 'Instrument Panel Circuit Board'},
    //  { name: 'Instrument Panel Cover'},
    //  { name: 'Instrument Panel Harness Connector'},
    //  { name: 'Intake Boot'},
    //  { name: 'Intake Manifold'},
    //  { name: 'Intake Manifold Actuator'},
    //  { name: 'Intake Manifold Adjuster Repair Kit'},
    //  { name: 'Intake Manifold and Carburetor Kit'},
    //  { name: 'Intake Manifold and Valve Cover Kit'},
    //  { name: 'Intake Manifold Cover'},
    //  { name: 'Intake Manifold Flap Motor'},
    //  { name: 'Intake Manifold Gasket'},
    //  { name: 'Intake Manifold Gasket Set'},
    //  { name: 'Intake Manifold Hose'},
    //  { name: 'Intake Manifold Motor'},
    //  { name: 'Intake Manifold Position Sensor'},
    //  { name: 'Intake Manifold Runner'},
    //  { name: 'Intake Manifold Runner Control Lever'},
    //  { name: 'Intake Manifold Runner Control Motor'},
    //  { name: 'Intake Manifold Runner Solenoid'},
    //  { name: 'Intake Manifold Runner Valve'},
    //  { name: 'Intake Plenum Gasket'},
    //  { name: 'Intake Plenum Gasket Set'},
    //  { name: 'Intake Runner Control Module'},
    //  { name: 'Intake Valve'},
    //  { name: 'Intercooler'},
    //  { name: 'Intercooler Pipe'},
    //  { name: 'Interior Door Handle'},
    //  { name: 'Interior Door Handle Bezel'},
    //  { name: 'Interior Door Handle Bezel Set'},
    //  { name: 'Interior Door Handle Latch Cable'},
    //  { name: 'Interior Door Handle Set'},
    //  { name: 'Interior Door Pull Handle'},
    //  { name: 'Interior Door Pull Handle Set'},
    //  { name: 'Interior Light Bulb'},
    //  { name: 'Intermediate Pipe'},
    //  { name: 'Intermediate Shaft Bearing Tool Set'},
    //  { name: 'Intermediate Shaft Bearing Update Kit'},
    //  { name: 'Inverter Cooler'},
    //  { name: 'Inverter Cooler Water Pump'},
    //  { name: 'Jack'},
    //  { name: 'Keyless Remote Case'},
    //  { name: 'Kick Panel'},
    //  { name: 'Knock Sensor'},
    //  { name: 'Knock Sensor and Manifold Gasket Set'},
    //  { name: 'Knock Sensor Harness'},
    //  { name: 'Knock Sensor Kit'},
    //  { name: 'Knuckle Bushing'},
    //  { name: 'Lateral Arm'},
    //  { name: 'Lateral Arm Bolt'},
    //  { name: 'Lateral Link and Ball Joint Assembly'},
    //  { name: 'Leaf Helper Spring'},
    //  { name: 'Leaf Spring'},
    //  { name: 'Leaf Spring Axle U-Bolt Kit'},
    //  { name: 'Leaf Spring Bushing'},
    //  { name: 'Leaf Spring Hanger'},
    //  { name: 'Leaf Spring Hanger Kit Rear'},
    //  { name: 'Leaf Spring Shackle'},
    //  { name: 'Leaf Spring Shackle and Bracket Kit'},
    //  { name: 'Leaf Spring Shackle Bracket'},
    //  { name: 'Leaf Spring Shackle Set'},
    //  { name: 'Leaf Spring Shackle/Bracket Kit'},
    //  { name: 'Leak Detection Pump'},
    //  { name: 'License Lamp Connector'},
    //  { name: 'License Lamp Lense'},
    //  { name: 'License Lamp Socket'},
    //  { name: 'License Light Lens'},
    //  { name: 'License Plate Bracket'},
    //  { name: 'License Plate Light Lens Set'},
    //  { name: 'License Plate Retainer'},
    //  { name: 'Liftgate'},
    //  { name: 'Liftgate Control Module'},
    //  { name: 'Liftgate Glass Hinge'},
    //  { name: 'Liftgate Handle'},
    //  { name: 'Liftgate Latch'},
    //  { name: 'Liftgate Latch Handle'},
    //  { name: 'Liftgate Lift Support'},
    //  { name: 'Liftgate Lift Support Set'},
    //  { name: 'Liftgate Lock Actuator'},
    //  { name: 'Liftgate Pull Handle'},
    //  { name: 'Liftgate Release Motor'},
    //  { name: 'Liftgate Release Switch'},
    //  { name: 'Light and Rain Sensor'},
    //  { name: 'Light Control Relay'},
    //  { name: 'Lighting Control Module'},
    //  { name: 'Link Bushing'},
    //  { name: 'Linkage Assembly'},
    //  { name: 'Locking Hub'},
    //  { name: 'Locking Hub Actuator'},
    //  { name: 'Locking Hub Kit'},
    //  { name: 'Lower Engine Cover'},
    //  { name: 'Lug Nut'},
    //  { name: 'M/T Fluid'},
    //  { name: 'M/T Shift Cable'},
    //  { name: 'Main Bearing Set'},
    //  { name: 'Main Relay'},
    //  { name: 'Manifold Absolute Pressure Sensor Kit'},
    //  { name: 'Manual Trans Bearing and Seal Overhaul Kit'},
    //  { name: 'Manual Trans Bellhousing Kit'},
    //  { name: 'Manual Trans Shift Cable'},
    //  { name: 'Manual Trans Shift Cable Bushing'},
    //  { name: 'Manual Trans Shifter Lever Kit'},
    //  { name: 'Manual Trans Shifter Repair Kit'},
    //  { name: 'MAP Sensor'},
    //  { name: 'Mass Air Flow Sensor'},
    //  { name: 'Mass Air Flow Sensor Assembly'},
    //  { name: 'Mechanical Fuel Pump'},
    //  { name: 'Mirror'},
    //  { name: 'Mirror Glass'},
    //  { name: 'Mirror Set'},
    //  { name: 'Mirror Switch'},
    //  { name: 'Mud Flaps'},
    //  { name: 'Muffler'},
    //  { name: 'Muffler Hanger Kit'},
    //  { name: 'Muffler Kit'},
    //  { name: 'Muffler Strap'},
    //  { name: 'Multi Function Switch'},
    //  { name: 'Multi Rib Belt'},
    //  { name: 'Nerf Bars'},
    //  { name: 'Neutral Safety Switch'},
    //  { name: 'Nitrogen Oxide Sensor'},
    //  { name: 'NOx (Nitrogen Oxide) Sensor'},
    //  { name: 'Object Sensor Module'},
    //  { name: 'Oil Cooler'},
    //  { name: 'Oil Cooler Gasket Set'},
    //  { name: 'Oil Cooler Hose'},
    //  { name: 'Oil Cooler Line'},
    //  { name: 'Oil Cooler Seal Kit'},
    //  { name: 'Oil Deep Sump Kit'},
    //  { name: 'Oil Dipstick'},
    //  { name: 'Oil Dipstick and Tube Set'},
    //  { name: 'Oil Dipstick Funnel'},
    //  { name: 'Oil Dipstick Tube'},
    //  { name: 'Oil Dipstick Tube Funnel'},
    //  { name: 'Oil Filler Cap'},
    //  { name: 'Oil Filter'},
    //  { name: 'Oil Filter Adapter'},
    //  { name: 'Oil Filter Housing'},
    //  { name: 'Oil Filter Housing Cap'},
    //  { name: 'Oil Filter Kit'},
    //  { name: 'Oil Filter Wrench'},
    //  { name: 'Oil Level Sender'},
    //  { name: 'Oil Pan'},
    //  { name: 'Oil Pan Gasket'},
    //  { name: 'Oil Pan Gasket Set'},
    //  { name: 'Oil Pick-up Tube O-Ring'},
    //  { name: 'Oil Pressure Relief Valve'},
    //  { name: 'Oil Pressure Sender'},
    //  { name: 'Oil Pressure Tube'},
    //  { name: 'Oil Pump'},
    //  { name: 'Oil Pump Cover'},
    //  { name: 'Oil Pump Repair Kit'},
    //  { name: 'Oil Pump Seal'},
    //  { name: 'Oil Pump Solenoid'},
    //  { name: 'Oil Separator'},
    //  { name: 'Oil Thermostat'},
    //  { name: 'Outside Door Handle'},
    //  { name: 'Outside Door Handle Reinforcement'},
    //  { name: 'Overhead Console Light Housing'},
    //  { name: 'Overhead Console Switch'},
    //  { name: 'Overload Protection Relay'},
    //  { name: 'Oxygen Sensor'},
    //  { name: 'Oxygen Sensor Nut'},
    //  { name: 'Oxygen Sensor Set'},
    //  { name: 'Paper Repair Manual'},
    //  { name: 'Park Assist Camera'},
    //  { name: 'Park Position Switch'},
    //  { name: 'Parking / Turn Signal / Stop Light Connector'},
    //  { name: 'Parking Brake Actuator'},
    //  { name: 'Parking Brake Actuator Repair Kit'},
    //  { name: 'Parking Brake Assembly'},
    //  { name: 'Parking Brake Cable'},
    //  { name: 'Parking Brake Handle Assembly'},
    //  { name: 'Parking Brake Kit'},
    //  { name: 'Parking Brake Lever Kit'},
    //  { name: 'Parking Brake Pad Set'},
    //  { name: 'Parking Brake Release Handle'},
    //  { name: 'Parking Brake Switch'},
    //  { name: 'Parking Distance Sensor'},
    //  { name: 'Parking Light'},
    //  { name: 'Parking Light Assembly'},
    //  { name: 'Parking Light Bulb Socket'},
    //  { name: 'Parking Light Set'},
    //  { name: 'Passenger Air Bag Disable Switch'},
    //  { name: 'PCV Hose'},
    //  { name: 'PCV Valve Cover Repair Kit'},
    //  { name: 'PCV Valve Diaphragm'},
    //  { name: 'PCV Valve Oil Separator Kit'},
    //  { name: 'PCV Valve Oil Trap'},
    //  { name: 'PCV Valve Tubing'},
    //  { name: 'Pickup Bed Floor Patch Set'},
    //  { name: 'Pickup Bed Floor Support'},
    //  { name: 'Pickup Bed Panel'},
    //  { name: 'Pickup Bed Side Moulding'},
    //  { name: 'Pickup Cab Back Panel'},
    //  { name: 'Pickup Cab Corner'},
    //  { name: 'Piston'},
    //  { name: 'Piston & Cylinder Set'},
    //  { name: 'Piston Ring Set'},
    //  { name: 'Piston Set'},
    //  { name: 'Pitman Arm'},
    //  { name: 'Power Antenna'},
    //  { name: 'Power Antenna Mast'},
    //  { name: 'Power Brake Booster Vacuum Pump'},
    //  { name: 'Power Brake Booster with Brake Master Cylinder'},
    //  { name: 'Power Control Module'},
    //  { name: 'Power Liftgate Actuator'},
    //  { name: 'Power Seat Switch'},
    //  { name: 'Power Sliding Door Cable'},
    //  { name: 'Power Sliding Door Motor'},
    //  { name: 'Power Steering Air Control Valve'},
    //  { name: 'Power Steering Assist Motor'},
    //  { name: 'Power Steering Assist Motor Coupling Gear'},
    //  { name: 'Power Steering Control Module Connector'},
    //  { name: 'Power Steering Control Valve'},
    //  { name: 'Power Steering Control Valve Bypass Tube'},
    //  { name: 'Power Steering Control Valve Rebuilt Kit'},
    //  { name: 'Power Steering Cooler'},
    //  { name: 'Power Steering Cooling Line'},
    //  { name: 'Power Steering Fluid'},
    //  { name: 'Power Steering Hose Assembly'},
    //  { name: 'Power Steering Hose Connector'},
    //  { name: 'Power Steering Hose Kit'},
    //  { name: 'Power Steering Hose O-Ring'},
    //  { name: 'Power Steering Oil Pressure Switch'},
    //  { name: 'Power Steering Pressure Hose'},
    //  { name: 'Power Steering Pressure Line Hose Assembly'},
    //  { name: 'Power Steering Pump'},
    //  { name: 'Power Steering Pump Complete Kit'},
    //  { name: 'Power Steering Pump Fan Assembly'},
    //  { name: 'Power Steering Pump Pulley'},
    //  { name: 'Power Steering Reservoir'},
    //  { name: 'Power Steering Reservoir Line Hose'},
    //  { name: 'Power Steering Return Hose'},
    //  { name: 'Power Steering Return Line Hose Assembly'},
    //  { name: 'Power Take Off Assembly'},
    //  { name: 'Power Vent Window Motor'},
    //  { name: 'Power Window Motor Gear'},
    //  { name: 'Power Window Regulator Assembly'},
    //  { name: 'Powertrain Control Module Relay'},
    //  { name: 'Preglow Time Relay'},
    //  { name: 'Pressure Plate'},
    //  { name: 'Pressure Plate and Disc Set'},
    //  { name: 'Pressure Sensor'},
    //  { name: 'Primer Pump'},
    //  { name: 'Primer Pump Assembly'},
    //  { name: 'Purge Valve'},
    //  { name: 'Push To Start Switch'},
    //  { name: 'Quarter Panel'},
    //  { name: 'Quarter Panel Patch'},
    //  { name: 'Quarter Panel Patch Set'},
    //  { name: 'Rack and Pinion Hydraulic Transfer Tubing Assembly'},
    //  { name: 'Rack and Pinion Mount Bushing'},
    //  { name: 'Radiator'},
    //  { name: 'Radiator And A/C Condenser Assembly'},
    //  { name: 'Radiator and Hose Kit'},
    //  { name: 'Radiator Cap'},
    //  { name: 'Radiator Coolant Hose Adapter'},
    //  { name: 'Radiator Fan Assembly'},
    //  { name: 'Radiator Fan Motor'},
    //  { name: 'Radiator Fan Shroud'},
    //  { name: 'Radiator Filler Neck'},
    //  { name: 'Radiator Grille Shutter Assembly'},
    //  { name: 'Radiator Hose'},
    //  { name: 'Radiator Mount Bracket'},
    //  { name: 'Radiator Shutter Assembly'},
    //  { name: 'Radiator Shutter Housing'},
    //  { name: 'Radiator Support'},
    //  { name: 'Radiator Support Air Duct'},
    //  { name: 'Radiator Support Baffle'},
    //  { name: 'Radiator Support Baffle Clip'},
    //  { name: 'Radiator Support Bracket'},
    //  { name: 'Radiator Support Cover'},
    //  { name: 'Radiator Support Seal'},
    //  { name: 'Radiator Support Splash Shield'},
    //  { name: 'Radiator Support Tie Bar'},
    //  { name: 'Radio Antenna'},
    //  { name: 'Radio Antenna Mast'},
    //  { name: 'Radio Installation Kit'},
    //  { name: 'Radio Knob'},
    //  { name: 'Radius Arm'},
    //  { name: 'Radius Arm Bracket'},
    //  { name: 'Radius Arm Bushing Kit Chassis'},
    //  { name: 'Radius Rod'},
    //  { name: 'Radius Rod Bushing'},
    //  { name: 'Rear Fender'},
    //  { name: 'Rear View Mirror'},
    //  { name: 'Rear Window Wiper Motor Connector'},
    //  { name: 'Reduction Agent Heater Repair Kit'},
    //  { name: 'Reference Sensor'},
    //  { name: 'Reflector Housing'},
    //  { name: 'Relay'},
    //  { name: 'Relay Module'},
    //  { name: 'Release Bearing'},
    //  { name: 'Release Bearing and Slave Cylinder Assembly'},
    //  { name: 'Release Bearing Retaining Spring'},
    //  { name: 'Remote Control Transmitter for Keyless Entry / Alarm System'},
    //  { name: 'Remote Key Transmitter'},
    //  { name: 'Reservoir Level Sensor'},
    //  { name: 'Rocker Arm'},
    //  { name: 'Rocker Arm Kit'},
    //  { name: 'Rocker Panel Molding'},
    //  { name: 'Rocker Panel Molding Retainer'},
    //  { name: 'Rocker Panel Set'},
    //  { name: 'Rod Bearing Set'},
    //  { name: 'Roll Pan'},
    //  { name: 'Roof Clearance Light Socket'},
    //  { name: 'Roof Marker Light'},
    //  { name: 'Roof Panel'},
    //  { name: 'Roof Weatherstrip Channel'},
    //  { name: 'Running Board'},
    //  { name: 'Running Board Kit'},
    //  { name: 'Running Board Lamp Socket'},
    //  { name: 'Running Board Motor'},
    //  { name: 'Running Board Mount Kit'},
    //  { name: 'Running Board Set'},
    //  { name: 'Running Boards'},
    //  { name: 'Sealed Beam Headlight'},
    //  { name: 'Seat Adjustment Handle'},
    //  { name: 'Seat Belt Guide'},
    //  { name: 'Seat Cushion Assembly'},
    //  { name: 'Seat Cushion Foam'},
    //  { name: 'Seat Gear'},
    //  { name: 'Seat Heater Switch'},
    //  { name: 'Seat Hinge Cover'},
    //  { name: 'Seat Knob'},
    //  { name: 'Seat Lumbar Switch'},
    //  { name: 'Seat Motor'},
    //  { name: 'Seat Mounting Bracket'},
    //  { name: 'Seat Rail'},
    //  { name: 'Seat Riser'},
    //  { name: 'Seat Switch'},
    //  { name: 'Seat Switch Panel'},
    //  { name: 'Seat Track Cover'},
    //  { name: 'Seat Track Position Sensor Connector'},
    //  { name: 'Secondary Air Injection Air Mass Sensor'},
    //  { name: 'Secondary Air Injection By-Pass Valve'},
    //  { name: 'Secondary Air Injection Check Valve'},
    //  { name: 'Secondary Air Injection Control Valve'},
    //  { name: 'Secondary Air Injection Pump'},
    //  { name: 'Secondary Air Injection Relay'},
    //  { name: 'Secondary Air Injection Shut-Off Valve'},
    //  { name: 'Secondary Air Injection Shut-Off Valve Pressure Sensor'},
    //  { name: 'Serpentine Belt Drive Component Kit'},
    //  { name: 'Shift Interlock Latch'},
    //  { name: 'Shift Interlock Module'},
    //  { name: 'Shift Rod Coupling'},
    //  { name: 'Shifter Bushing Kit'},
    //  { name: 'Shock Absorber'},
    //  { name: 'Shock Absorber and Coil Spring Assembly Kit'},
    //  { name: 'Shock Absorber and Coil Spring Assembly Set'},
    //  { name: 'Shock Absorber Conversion Kit'},
    //  { name: 'Shock Absorber Kit'},
    //  { name: 'Shock Absorber Set'},
    //  { name: 'Shock and Coil Spring Kit'},
    //  { name: 'Shock and Strut Mount Kit'},
    //  { name: 'Shock and Sway Bar Link Kit'},
    //  { name: 'Shock Bellows'},
    //  { name: 'Shock Bump Stop'},
    //  { name: 'Shock Bumper'},
    //  { name: 'Shock Bushing'},
    //  { name: 'Shock Coil Spring Control Arm Kit'},
    //  { name: 'Shock Coil Spring Sway Bar Link Kit'},
    //  { name: 'Shock Mount'},
    //  { name: 'Shock Mount Plate'},
    //  { name: 'Shock Strut and Coil Spring Kit'},
    //  { name: 'Shock Strut Coil Spring Control Arm Kit'},
    //  { name: 'Shock Strut Coil Spring Sway Bar Link Kit'},
    //  { name: 'Shock Strut Coil Spring Wheel Hub Kit'},
    //  { name: 'Shock Tower Patch Panel'},
    //  { name: 'Shut Off Valve'},
    //  { name: 'Side Body Panel'},
    //  { name: 'Side Marker'},
    //  { name: 'Side Marker Assembly'},
    //  { name: 'Side Marker Lamp Connector'},
    //  { name: 'Side Marker Lamp Socket Connector'},
    //  { name: 'Side Marker Lens'},
    //  { name: 'Side Marker Light'},
    //  { name: 'Side Marker Light Assembly'},
    //  { name: 'Side Marker Light Set'},
    //  { name: 'Side Marker Light Socket'},
    //  { name: 'Side Sliding Door Roller Assembly'},
    //  { name: 'Side Sliding Door Roller Assembly Kit'},
    //  { name: 'Side Sliding Door Roller Bracket'},
    //  { name: 'Side Window Deflector'},
    //  { name: 'Signal Acquisition Module Control Unit'},
    //  { name: 'Skid Plate'},
    //  { name: 'Sliding Door Contact Assembly'},
    //  { name: 'Sliding Door Motor Harness'},
    //  { name: 'Soft Top'},
    //  { name: 'Soft Top Bow Bracket Kit'},
    //  { name: 'Soft Top Hardware Kit'},
    //  { name: 'Spare Tire'},
    //  { name: 'Spare Tire Braces'},
    //  { name: 'Spare Tire Hoist'},
    //  { name: 'Spare Tire Jack Handle / Wheel Lug Wrench'},
    //  { name: 'Spare Tire Well'},
    //  { name: 'Spark Plug'},
    //  { name: 'Spark Plug Seal'},
    //  { name: 'Spark Plug Wire'},
    //  { name: 'Spark Plug Wire Holder'},
    //  { name: 'Spark Plug Wire Set'},
    //  { name: 'Speaker Cover'},
    //  { name: 'Speedometer Cable'},
    //  { name: 'Speedometer Sensor'},
    //  { name: 'Splash Shield Hardware'},
    //  { name: 'Splash Shield Retainer'},
    //  { name: 'Spoiler'},
    //  { name: 'Spoiler Kit'},
    //  { name: 'Spoiler Retainer'},
    //  { name: 'Spring Seat'},
    //  { name: 'Stability Control Steering Angle Sensor'},
    //  { name: 'Stabilizer Bar'},
    //  { name: 'Stabilizer Bar Assembly'},
    //  { name: 'Stabilizer Bar Bushing Kit'},
    //  { name: 'Stabilizer Bar Link'},
    //  { name: 'Stabilizer Bar Link Kit'},
    //  { name: 'Stainless Steel Fender Trim'},
    //  { name: 'Starter'},
    //  { name: 'Steering Angle Sensor'},
    //  { name: 'Steering Angle Sensor Connector'},
    //  { name: 'Steering Column'},
    //  { name: 'Steering Column Housing Repair Kit'},
    //  { name: 'Steering Column Intermediate Shaft'},
    //  { name: 'Steering Column Lock Actuator'},
    //  { name: 'Steering Column Repair Kit'},
    //  { name: 'Steering Column Shift Mechanism'},
    //  { name: 'Steering Coupling'},
    //  { name: 'Steering Damper'},
    //  { name: 'Steering Damper Kit'},
    //  { name: 'Steering Gear'},
    //  { name: 'Steering Gear Box Brace Bar'},
    //  { name: 'Steering Gearbox'},
    //  { name: 'Steering Knuckle'},
    //  { name: 'Steering Knuckle Kit'},
    //  { name: 'Steering Knuckle Seal'},
    //  { name: 'Steering Knuckle Set'},
    //  { name: 'Steering Linkage Assembly'},
    //  { name: 'Steering Linkage Conversion Kit'},
    //  { name: 'Steering Rack'},
    //  { name: 'Steering Rack and Tie Rod End Kit'},
    //  { name: 'Steering Rack Boot'},
    //  { name: 'Steering Rack Boot Kit'},
    //  { name: 'Steering Rack Bushing'},
    //  { name: 'Steering Rack Bushing Kit'},
    //  { name: 'Steering Rack Control Arm Ball Joint Kit'},
    //  { name: 'Steering Shaft'},
    //  { name: 'Steering Shaft Universal Joint'},
    //  { name: 'Steering Wheel Audio Control Switch'},
    //  { name: 'Step'},
    //  { name: 'Step Bumper'},
    //  { name: 'Step Bumper Pad'},
    //  { name: 'Stop Light Switch'},
    //  { name: 'Strut / Coil Spring Assembly'},
    //  { name: 'Strut and Coil Spring Assembly'},
    //  { name: 'Strut and Coil Spring Assembly Set'},
    //  { name: 'Strut Assembly'},
    //  { name: 'Strut Assembly Kit'},
    //  { name: 'Strut Assembly Set'},
    //  { name: 'Strut Bellows'},
    //  { name: 'Strut Coil Spring and Control Arm Kit'},
    //  { name: 'Strut Coil Spring Ball Joint Kit'},
    //  { name: 'Strut Coil Spring Ball Joint Tie Rod Kit'},
    //  { name: 'Strut Coil Spring Control Arm Kit'},
    //  { name: 'Strut Coil Spring Control Arm Tie Rod Kit'},
    //  { name: 'Strut Coil Spring Sway Bar Link Kit'},
    //  { name: 'Strut Insert'},
    //  { name: 'Strut Mount'},
    //  { name: 'Strut Mount Kit'},
    //  { name: 'Strut Mounting Kit'},
    //  { name: 'Strut Rod Bushing'},
    //  { name: 'Stub Axle'},
    //  { name: 'Subframe Bushing'},
    //  { name: 'Subframe Bushing Kit'},
    //  { name: 'Subframe Mount'},
    //  { name: 'Sun Visor'},
    //  { name: 'Sun Visor Clip'},
    //  { name: 'Sun Visor Holder Clip'},
    //  { name: 'Sun Visor Set'},
    //  { name: 'Sunroof Drain Hose Grommet'},
    //  { name: 'Sunroof Frame Repair Kit'},
    //  { name: 'Sunroof Motor'},
    //  { name: 'Sunroof Seal'},
    //  { name: 'Sunvisor Bracket'},
    //  { name: 'Supercharger Pulley Bearing'},
    //  { name: 'Suspension Air Compressor Filter'},
    //  { name: 'Suspension Air Helper Spring Kit'},
    //  { name: 'Suspension Air Strut'},
    //  { name: 'Suspension Air Strut Set'},
    //  { name: 'Suspension Bellows'},
    //  { name: 'Suspension Body Lowering Kit'},
    //  { name: 'Suspension Bushing Kit'},
    //  { name: 'Suspension Compressor'},
    //  { name: 'Suspension Compressor Valve'},
    //  { name: 'Suspension Control Arm Kit'},
    //  { name: 'Suspension Conversion Kit'},
    //  { name: 'Suspension Fluid'},
    //  { name: 'Suspension Kit'},
    //  { name: 'Suspension Knuckle'},
    //  { name: 'Suspension Knuckle Assembly'},
    //  { name: 'Suspension Knuckle Kit'},
    //  { name: 'Suspension Lift Kit'},
    //  { name: 'Suspension Pump'},
    //  { name: 'Suspension Ride Height Sensor'},
    //  { name: 'Suspension Ride Height Sensor Set'},
    //  { name: 'Suspension Rubber Helper Spring Kit'},
    //  { name: 'Suspension Self-Leveling Unit Line'},
    //  { name: 'Suspension Self-Leveling Valve'},
    //  { name: 'Suspension Sensor'},
    //  { name: 'Suspension Strut and Shock Absorber Assembly Kit'},
    //  { name: 'Suspension Strut Mount Kit'},
    //  { name: 'Suspension Subframe'},
    //  { name: 'Suspension Subframe Crossmember'},
    //  { name: 'Suspension Valve'},
    //  { name: 'Sway Bar Bracket'},
    //  { name: 'Sway Bar Bushing'},
    //  { name: 'Sway Bar Bushing Kit'},
    //  { name: 'Sway Bar Link'},
    //  { name: 'Sway Bar Link and Bushing Kit'},
    //  { name: 'Sway Bar Link and Trailing Arm Kit'},
    //  { name: 'Sway Bar Link Bushing'},
    //  { name: 'Sway Bar Link Kit'},
    //  { name: 'Switch'},
    //  { name: 'Switch (4WD)'},
    //  { name: 'T-Belt Tension Adjuster'},
    //  { name: 'T-Belt Tension Assembly'},
    //  { name: 'T-Top Kit'},
    //  { name: 'Tachometer Sensor'},
    //  { name: 'Tail Lamp Socket'},
    //  { name: 'Tail Light Assembly'},
    //  { name: 'Tail Light Assembly Set'},
    //  { name: 'Tail Light Bulb'},
    //  { name: 'Tail Light Bulb Carrier'},
    //  { name: 'Tail Light Bulb Holder'},
    //  { name: 'Tail Light Circuit Board Connector'},
    //  { name: 'Tail Light Connector'},
    //  { name: 'Tail Light Connector Plate'},
    //  { name: 'Tail Light Covers'},
    //  { name: 'Tail Light Harness'},
    //  { name: 'Tail Light Lens'},
    //  { name: 'Tail Light Lens Assembly'},
    //  { name: 'Tail Light Lens Set'},
    //  { name: 'Tail Light PC Board'},
    //  { name: 'Tail Light Set'},
    //  { name: 'Tail Light Support Panel'},
    //  { name: 'Tail Pipe'},
    //  { name: 'Tailgate'},
    //  { name: 'Tailgate Access Cover'},
    //  { name: 'Tailgate Cable'},
    //  { name: 'Tailgate Cap Protector'},
    //  { name: 'Tailgate Chain'},
    //  { name: 'Tailgate Extender'},
    //  { name: 'Tailgate Handle'},
    //  { name: 'Tailgate Handle and Bezel Kit'},
    //  { name: 'Tailgate Handle Bezel'},
    //  { name: 'Tailgate Hinge'},
    //  { name: 'Tailgate Hinge Bushing'},
    //  { name: 'Tailgate Hinge Kit'},
    //  { name: 'Tailgate Hinge Set'},
    //  { name: 'Tailgate Lift Support Kit'},
    //  { name: 'Tailgate Liner'},
    //  { name: 'Tailgate Lock'},
    //  { name: 'Tailgate Lock Actuator Motor'},
    //  { name: 'Tailgate Molding'},
    //  { name: 'Tailgate Moulding'},
    //  { name: 'Tailgate Net'},
    //  { name: 'Tailgate Panel'},
    //  { name: 'Tailgate Panel Kit'},
    //  { name: 'Tailgate Protector'},
    //  { name: 'Tailgate Pull Down Motor'},
    //  { name: 'Tailgate Release Switch'},
    //  { name: 'Tailgate Rubber Stop'},
    //  { name: 'Tailgate Spoiler'},
    //  { name: 'Tailgate Striker Bolt'},
    //  { name: 'Tailgate Strut'},
    //  { name: 'Tailgate Strut Set'},
    //  { name: 'Tailgate Support Cable'},
    //  { name: 'Tailgate Support Cable Set'},
    //  { name: 'Tailgate Window Motor'},
    //  { name: 'Tailgate Window Seal'},
    //  { name: 'Targa Top Seal'},
    //  { name: 'Tensioner Gasket Kit'},
    //  { name: 'Thermo Time Switch'},
    //  { name: 'Thermostat'},
    //  { name: 'Thermostat Assembly'},
    //  { name: 'Thermostat Bypass Pipe'},
    //  { name: 'Thermostat Housing'},
    //  { name: 'Thermostat Housing Cover'},
    //  { name: 'Thermostat Housing Gasket'},
    //  { name: 'Third Brake Light'},
    //  { name: 'Third Brake Light Cover'},
    //  { name: 'Throttle Actuator'},
    //  { name: 'Throttle Body'},
    //  { name: 'Throttle Body Motor'},
    //  { name: 'Throttle Body Repair Kit'},
    //  { name: 'Throttle Body Spacer'},
    //  { name: 'Throttle Bushing'},
    //  { name: 'Throttle Cable'},
    //  { name: 'Throttle Control Motor Connector'},
    //  { name: 'Throttle Position Sensor'},
    //  { name: 'Tie Rod'},
    //  { name: 'Tie Rod and Center Drag Link Kit'},
    //  { name: 'Tie Rod Assembly'},
    //  { name: 'Tie Rod Assembly Center Drag Link Kit'},
    //  { name: 'Tie Rod End'},
    //  { name: 'Tie Rod End Adjusting Sleeve'},
    //  { name: 'Tie Rod End and Adjusting Sleeve Kit'},
    //  { name: 'Tie Rod End and Ball Joint Kit'},
    //  { name: 'Tie Rod End and Drag Link Kit'},
    //  { name: 'Tie Rod End and Steering Bellows Kit'},
    //  { name: 'Tie Rod End and Sway Bar Link Kit'},
    //  { name: 'Tie Rod End and Track Bar Kit'},
    //  { name: 'Tie Rod End Idler Arm Pitman Arm Kit'},
    //  { name: 'Tie Rod End Kit'},
    //  { name: 'Tie Rod End Kit with Tool'},
    //  { name: 'Tie Rod End Set'},
    //  { name: 'Tie Rod End Track Bar Drag Link Kit'},
    //  { name: 'Tie Rod Ends Ball Joints Sway Bar Links Kit'},
    //  { name: 'Tie Rod Idler Arm and Center Link Kit'},
    //  { name: 'Timing Belt'},
    //  { name: 'Timing Belt Idler'},
    //  { name: 'Timing Belt Kit'},
    //  { name: 'Timing Belt Kit and Water Pump'},
    //  { name: 'Timing Belt Kit and Water Pump with Seals'},
    //  { name: 'Timing Belt Tensioner'},
    //  { name: 'Timing Camshaft Sprocket'},
    //  { name: 'Timing Chain'},
    //  { name: 'Timing Chain Kit'},
    //  { name: 'Timing Chain Tensioner'},
    //  { name: 'Timing Chain Tensioner Guide'},
    //  { name: 'Timing Cover'},
    //  { name: 'Timing Cover Gasket'},
    //  { name: 'Timing Cover Gasket Set'},
    //  { name: 'Timing Crankshaft'},
    //  { name: 'Timing Gear Kit'},
    //  { name: 'Timing Guide Rail'},
    //  { name: 'Timing Set'},
    //  { name: 'Timing Sprocket Kit'},
    //  { name: 'Timing Tool Set'},
    //  { name: 'Tire Pressure Monitoring System TPMS Sensor Service Kit'},
    //  { name: 'Toe Adjustment Link'},
    //  { name: 'Toe Compensator Link'},
    //  { name: 'Tonneau Cover'},
    //  { name: 'Torsion Bar Mount Set'},
    //  { name: 'Torsion Bar Mount Support'},
    //  { name: 'Tow Hook Cover'},
    //  { name: 'Towing Mirror'},
    //  { name: 'Towing Mirror Set'},
    //  { name: 'TPMS Sensor'},
    //  { name: 'TPMS Valve Kit'},
    //  { name: 'Track Bar'},
    //  { name: 'Trailer Brake Control'},
    //  { name: 'Trailer Brake Control Module'},
    //  { name: 'Trailer Hitch'},
    //  { name: 'Trailer Hitch Cover'},
    //  { name: 'Trailer Tow Harness'},
    //  { name: 'Trailer Tow Harness Connector'},
    //  { name: 'Trailer Tow Relay'},
    //  { name: 'Trailer Wiring Harness'},
    //  { name: 'Trailing Arm'},
    //  { name: 'Trailing Arm Bushing'},
    //  { name: 'Trailing Arm Bushing Set'},
    //  { name: 'Trailing Arm Set'},
    //  { name: 'Transfer Case Chain'},
    //  { name: 'Transfer Case Control Lever'},
    //  { name: 'Transfer Case Control Module'},
    //  { name: 'Transfer Case Flange'},
    //  { name: 'Transfer Case Fluid'},
    //  { name: 'Transfer Case Housing'},
    //  { name: 'Transfer Case Motor'},
    //  { name: 'Transfer Case Motor Gear'},
    //  { name: 'Transfer Case Output Shaft'},
    //  { name: 'Transfer Case Shifter Linkage Rod Bushings Kit'},
    //  { name: 'Transfer Case Switch'},
    //  { name: 'Transmission Control Module'},
    //  { name: 'Transmission Cooler'},
    //  { name: 'Transmission Crossmember'},
    //  { name: 'Transmission Dipstick Tool'},
    //  { name: 'Transmission Mount'},
    //  { name: 'Transmission Oil Cooler'},
    //  { name: 'Transmission Oil Temperature Sensor'},
    //  { name: 'Transmission Range Sensor'},
    //  { name: 'Transverse Link'},
    //  { name: 'Truck Bed Floor Patch Panel'},
    //  { name: 'Truck Bed Floor Support'},
    //  { name: 'Truck Bed Mounting Hardware'},
    //  { name: 'Truck Bed Rack Installation Kit'},
    //  { name: 'Truck Cab Mount'},
    //  { name: 'Truck Cab Side Step'},
    //  { name: 'Truck Step'},
    //  { name: 'Trunk Floor'},
    //  { name: 'Trunk Hatch Liftgate Switch Release Button Cover'},
    //  { name: 'Trunk Latch'},
    //  { name: 'Trunk Lid'},
    //  { name: 'Trunk Lid Lift Support Kit'},
    //  { name: 'Trunk Lid Pull Down Motor'},
    //  { name: 'Trunk Lid Pull Down Motor Kit'},
    //  { name: 'Trunk Lid Release Switch'},
    //  { name: 'Trunk Lid Weatherstrip'},
    //  { name: 'Trunk Lock'},
    //  { name: 'Trunk Lock Actuator Motor'},
    //  { name: 'Trunk Lock Assembly'},
    //  { name: 'Trunk Strut'},
    //  { name: 'Turbo Mounting Gasket Set'},
    //  { name: 'Turbo Oil line Gasket'},
    //  { name: 'Turbo Oil Return Tube'},
    //  { name: 'Turbocharger'},
    //  { name: 'Turbocharger Actuator'},
    //  { name: 'Turbocharger Boost Sensor'},
    //  { name: 'Turbocharger Boost Solenoid'},
    //  { name: 'Turbocharger Cartridge'},
    //  { name: 'Turbocharger Coolant Line'},
    //  { name: 'Turbocharger Diverter Valve'},
    //  { name: 'Turbocharger Inlet Hose'},
    //  { name: 'Turbocharger Inlet Pipe'},
    //  { name: 'Turbocharger Intercooler'},
    //  { name: 'Turbocharger Intercooler Hose'},
    //  { name: 'Turbocharger Intercooler Hose Kit'},
    //  { name: 'Turbocharger Intercooler Intake Silencer'},
    //  { name: 'Turbocharger Manifold'},
    //  { name: 'Turbocharger Mount'},
    //  { name: 'Turbocharger Oil Line'},
    //  { name: 'Turbocharger Up Pipe Kit'},
    //  { name: 'Turbocharger Wastegate'},
    //  { name: 'Turbocharger Wastegate Actuator'},
    //  { name: 'Turbocharger Wastegate Solenoid'},
    //  { name: 'Turbocharger with Exhaust Manifold'},
    //  { name: 'Turn Signal / Combination Lever'},
    //  { name: 'Turn Signal / Parking / Side Marker Light Assembly'},
    //  { name: 'Turn Signal / Parking Light'},
    //  { name: 'Turn Signal / Parking Light Assembly'},
    //  { name: 'Turn Signal / Side Marker Assembly'},
    //  { name: 'Turn Signal Assembly'},
    //  { name: 'Turn Signal Bulb Socket'},
    //  { name: 'Turn Signal Cruise Control Tilt Lever'},
    //  { name: 'Turn Signal Flasher'},
    //  { name: 'Turn Signal Lens'},
    //  { name: 'Turn Signal Lever'},
    //  { name: 'Turn Signal Light'},
    //  { name: 'Turn Signal Light Connector'},
    //  { name: 'Turn Signal Switch'},
    //  { name: 'U Joint'},
    //  { name: 'Undercar Shield'},
    //  { name: 'Undercar Shield Mounting Hardware'},
    //  { name: 'Underseat Storage Box'},
    //  { name: 'Universal Joint'},
    //  { name: 'Universal Lift Support'},
    //  { name: 'Vacuum Control Valve'},
    //  { name: 'Vacuum Hose'},
    //  { name: 'Vacuum Pump'},
    //  { name: 'Vacuum Pump Gasket'},
    //  { name: 'Vacuum Pump Repair Kit'},
    //  { name: 'Vacuum Supply Pump'},
    //  { name: 'Vacuum Switching Valve'},
    //  { name: 'Vacuum Tank'},
    //  { name: 'Vacuum Valve'},
    //  { name: 'Valance Panel'},
    //  { name: 'Valve Adjust Shim Kit'},
    //  { name: 'Valve Cover'},
    //  { name: 'Valve Cover Bolt'},
    //  { name: 'Valve Cover Gasket'},
    //  { name: 'Valve Cover Gasket Set'},
    //  { name: 'Valve Cover Kit'},
    //  { name: 'Valve Cover O-Ring'},
    //  { name: 'Valve Cover Repair Kit'},
    //  { name: 'Valve Cover Seal Washer'},
    //  { name: 'Valve Lifter'},
    //  { name: 'Valve Lifter Kit'},
    //  { name: 'Vapor Canister Filter'},
    //  { name: 'Vapor Canister Purge Solenoid'},
    //  { name: 'Vapor Canister Vent Solenoid'},
    //  { name: 'Vapor Canister Vent Valve'},
    //  { name: 'Variable Timing Solenoid'},
    //  { name: 'Variable Timing Solenoid Kit'},
    //  { name: 'Variable Timing Solenoid Socket'},
    //  { name: 'Variable Valve Lift Eccentric Shaft Actuator'},
    //  { name: 'Variable Valve Lift Eccentric Shaft Sensor'},
    //  { name: 'Vent Window Frame'},
    //  { name: 'Vent Window Latch'},
    //  { name: 'Vent Window Weatherstrip'},
    //  { name: 'Voltage Regulator'},
    //  { name: 'VVT Oil Control Valve'},
    //  { name: 'VVT Sprocket'},
    //  { name: 'Washer Fluid Reservoir Clip'},
    //  { name: 'Washer Hose'},
    //  { name: 'Washer Nozzle'},
    //  { name: 'Washer Pump'},
    //  { name: 'Washer Reservoir'},
    //  { name: 'Washer Reservoir Cap'},
    //  { name: 'Water Bypass Pipe'},
    //  { name: 'Water Distribution Pipe'},
    //  { name: 'Water in Fuel Sensor'},
    //  { name: 'Water Pipe'},
    //  { name: 'Water Pump'},
    //  { name: 'Water Pump and Fan Clutch Kit'},
    //  { name: 'Water Pump Bracket'},
    //  { name: 'Water Pump Fan Clutch Thermostat Kit'},
    //  { name: 'Water Pump Gasket Kit'},
    //  { name: 'Water Pump Housing'},
    //  { name: 'Water Pump Pulley'},
    //  { name: 'Water Temperature Sensor'},
    //  { name: 'Watts Link'},
    //  { name: 'Wheel'},
    //  { name: 'Wheel Arch'},
    //  { name: 'Wheel Arch Patch'},
    //  { name: 'Wheel Arch Trim'},
    //  { name: 'Wheel Bearing'},
    //  { name: 'Wheel Bearing Assembly'},
    //  { name: 'Wheel Bearing Assembly Set'},
    //  { name: 'Wheel Bearing Bolt'},
    //  { name: 'Wheel Bearing Circlip'},
    //  { name: 'Wheel Bearing Kit'},
    //  { name: 'Wheel Bearing Retainer'},
    //  { name: 'Wheel Cap'},
    //  { name: 'Wheel Cap Set'},
    //  { name: 'Wheel Cover'},
    //  { name: 'Wheel Cylinder'},
    //  { name: 'Wheel Housing Reinforcement'},
    //  { name: 'Wheel Hub'},
    //  { name: 'Wheel Hub and Ball Joint Kit'},
    //  { name: 'Wheel Hub and Bearing Kit'},
    //  { name: 'Wheel Hub Assembly'},
    //  { name: 'Wheel Hub Assembly and Locking Hub Actuator Kit'},
    //  { name: 'Wheel Hub Assembly and Socket Kit'},
    //  { name: 'Wheel Hub Assembly and Tie Rod End Kit'},
    //  { name: 'Wheel Hub Assembly Set'},
    //  { name: 'Wheel Hub Ball Joint Tie Rod End Kit'},
    //  { name: 'Wheel Hub Control Arm Ball Joint Kit'},
    //  { name: 'Wheel Hub Flange'},
    //  { name: 'Wheel Hub Repair Kit'},
    //  { name: 'Wheel Hub Sway Bar Link Tie Rod Kit'},
    //  { name: 'Wheel Hub Tie Rod End Ball Joint Kit'},
    //  { name: 'Wheel Lug Bolt'},
    //  { name: 'Wheel Nut Cover'},
    //  { name: 'Wheel Seal'},
    //  { name: 'Wheel Speed Sensor Connector'},
    //  { name: 'Wheel Trim Ring'},
    //  { name: 'Wheelhouse Molding'},
    //  { name: 'Wheelhouse Moulding'},
    //  { name: 'Winch Mount Plate'},
    //  { name: 'Window Channel'},
    //  { name: 'Window Crank Handle'},
    //  { name: 'Window Crank Handle Set'},
    //  { name: 'Window Guide'},
    //  { name: 'Window Motor'},
    //  { name: 'Window Motor / Regulator Assembly'},
    //  { name: 'Window Regulator'},
    //  { name: 'Window Regulator Clip'},
    //  { name: 'Window Regulator Kit'},
    //  { name: 'Window Regulator Repair Kit'},
    //  { name: 'Window Regulator Rivet'},
    //  { name: 'Window Regulator Roller'},
    //  { name: 'Window Regulator Set'},
    //  { name: 'Window Switch'},
    //  { name: 'Window Switch Bezel'},
    //  { name: 'Window Switch Panel Assembly'},
    //  { name: 'Window Switch Set'},
    //  { name: 'Window Trim'},
    //  { name: 'Window Vent Visors'},
    //  { name: 'Windshield Bracket'},
    //  { name: 'Windshield Frame'},
    //  { name: 'Windshield Molding'},
    //  { name: 'Windshield Molding Seal'},
    //  { name: 'Windshield Molding Set'},
    //  { name: 'Windshield Moulding Clip'},
    //  { name: 'Windshield Post Trim'},
    //  { name: 'Windshield Seal'},
    //  { name: 'Windshield Washer Check Valve'},
    //  { name: 'Windshield Washer Fluid Reservoir Cap'},
    //  { name: 'Windshield Washer Nozzle'},
    //  { name: 'Windshield Washer Nozzle Set'},
    //  { name: 'Windshield Washer Tank'},
    //  { name: 'Windshield Washer Tank Filler Neck'},
    //  { name: 'Windshield Wiper Arm'},
    //  { name: 'Windshield Wiper Arm Set'},
    //  { name: 'Windshield Wiper Control Module'},
    //  { name: 'Windshield Wiper Linkage'},
    //  { name: 'Windshield Wiper Linkage Bushing'},
    //  { name: 'Windshield Wiper Motor'},
    //  { name: 'Windshield Wiper Motor Cover'},
    //  { name: 'Windshield Wiper Motor Transmission Linkage'},
    //  { name: 'Winter and Bug Grille Screen Kit'},
    //  { name: 'Wiper Blade'},
    //  { name: 'Wiper Blade Insert'},
    //  { name: 'Wiper Blade Insert Set'},
    //  { name: 'Wiper Blade Set'},
    //  { name: 'Wiper Linkage'},
    //  { name: 'Wiper Linkage & Motor Assembly'},
    //  { name: 'Wiper Motor Pulse Board Kit'},
    //  { name: 'Wiper Motor Pulse Board Module'},
    //  { name: 'Wiper Pivot Assembly'},
    //  { name: 'Wiper Relay'},
    //  { name: 'Wiper Switch'},
    //  { name: 'Wiring Harness'},
    //  { name: 'Xenon Headlight Control Unit'},
    //  { name: 'Xenon Headlight Igniter'},
    //  { name: 'Xenon Lighting Ballast'},
    //  { name: 'YAW Rate Sensor'},
    //   ]
    Parts_List.insertMany(arr).then(()=>{
        console.log("added")
        res.send('added');
    }
        )
  },
  getParts: (req, res) => {
      Parts_List.find().exec((err, doc)=>{
          if(err) return res.status(400).json({err: err.message})
          res.json({
              success: true,
              list : doc
          })
      })
  },
  
  getPartAddressbyWcId: (req, res) => {
    // Parts_List.find().exec((err, doc)=>{
    //     if(err) return res.status(400).json({err: err.message})
    //     res.json({
    //         success: true,
    //         list : doc
    //     })
    // })
},
getPartAddressById: (req, res) => {
    // Parts_List.find().exec((err, doc)=>{
    //     if(err) return res.status(400).json({err: err.message})
    //     res.json({
    //         success: true,
    //         list : doc
    //     })
    // })
}

}
module.exports = part_list